"""GENERATED by scripts/port_basketball_orchestrator.py (plan P6, lane basketball-native-orchestrator).

Native port of the definitions production EXECUTES from
  vendor/wnba_betting_repo/src/wnba_betting/boxscores.py (sha256 a5520481e2907172...)
checked definition by definition against
  vendor/nba_betting_repo/src/nba_betting/boxscores.py (sha256 f16f26f0f9f672cb...)
Ported: _tri_to_espn, _espn_to_tri, _espn_cache_dir, _read_json, _write_json, _http_get_json, _espn_scoreboard, _espn_summary, _espn_event_id_for_matchup.

Where the two forks differ, and how one text serves both:
  * _tri_to_espn: team-code table per league -> OrchestratorLeague.espn_tri_fix
  * _espn_to_tri: team-code table per league -> OrchestratorLeague.espn_abbr_fix
  * _http_get_json: 'nba-betting/1.0' literal vs LEAGUE.user_agent_product
  * _espn_scoreboard: sports/basketball/nba literal vs LEAGUE.espn_sport_path
  * _espn_summary: sports/basketball/nba literal vs LEAGUE.espn_sport_path

Anchored edits:
  * _tri_to_espn: team-code table per league
  * _espn_to_tri: team-code table per league

Mechanical edits: global `paths` / `LEAGUE` reads -> `orch.paths` / `orch.league` (runtime.OrchestratorEnv);
a keyword-only `orch` on every function that needs it, passed at every call; relative imports re-pointed
at this package. Calls to the 29 names Syndicate replaced go to hooks.py.

PARITY: scripts/basketball_orchestrator_parity.py replays recorded REAL production games through this
orchestrator and the vendored one, same seed, and compares every leaf of the output.
"""

from __future__ import annotations

import json
import time
from datetime import datetime as _dt
from pathlib import Path
from typing import Any, List, Optional, Tuple
import pandas as pd
import requests


def _tri_to_espn(tri: str, *, orch) -> str:
    s = str(tri or "").strip().upper()
    fix = dict(orch.league.espn_tri_fix)
    return fix.get(s, s)


def _espn_to_tri(abbr: str, *, orch) -> str:
    s = str(abbr or "").strip().upper()
    fix = dict(orch.league.espn_abbr_fix)
    return fix.get(s, s)


def _espn_cache_dir(*, orch) -> Path:
    d = orch.paths.data_processed / "_espn_cache"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _read_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _write_json(path: Path, data: dict[str, Any]) -> None:
    try:
        path.write_text(json.dumps(data), encoding="utf-8")
    except Exception:
        return


def _http_get_json(url: str, timeout: int = 18, *, orch) -> dict[str, Any]:
    try:
        r = requests.get(
            url,
            headers={"Accept": "application/json", "User-Agent": orch.league.user_agent_product},
            timeout=int(timeout),
        )
        if not r.ok:
            return {}
        j = r.json()
        return j if isinstance(j, dict) else {}
    except Exception:
        return {}


def _espn_scoreboard(date_str: str, *, force: bool = False, orch) -> dict[str, Any]:
    # ESPN expects YYYYMMDD
    ymd = str(date_str).replace("-", "")
    cache = _espn_cache_dir(orch=orch) / f"scoreboard_{ymd}.json"
    if (not force) and cache.exists():
        jd = _read_json(cache)
        if jd:
            return jd
    url = f"https://site.web.api.espn.com/apis/site/v2/{orch.league.espn_sport_path}/scoreboard?dates={ymd}"
    jd = _http_get_json(url, timeout=18, orch=orch)
    if jd:
        _write_json(cache, jd)
    return jd


def _espn_summary(event_id: str, *, force: bool = False, orch) -> dict[str, Any]:
    cache = _espn_cache_dir(orch=orch) / f"summary_{str(event_id).strip()}.json"
    if (not force) and cache.exists():
        jd = _read_json(cache)
        if jd:
            return jd
    url = f"https://site.web.api.espn.com/apis/site/v2/{orch.league.espn_sport_path}/summary?event={event_id}"
    jd = _http_get_json(url, timeout=18, orch=orch)
    if jd:
        _write_json(cache, jd)
    return jd


def _espn_event_id_for_matchup(date_str: str, home_tri: str, away_tri: str, *, force_scoreboard: bool = False, orch) -> Optional[str]:
    sb = _espn_scoreboard(date_str, force=bool(force_scoreboard), orch=orch)
    events = sb.get("events") if isinstance(sb, dict) else None
    if not isinstance(events, list):
        return None
    h = _tri_to_espn(home_tri, orch=orch)
    a = _tri_to_espn(away_tri, orch=orch)
    for e in events:
        try:
            comps = (e or {}).get("competitions") or []
            if not comps:
                continue
            c0 = comps[0] or {}
            teams = c0.get("competitors") or []
            if len(teams) < 2:
                continue
            home = next((t for t in teams if str((t or {}).get("homeAway")) == "home"), None)
            away = next((t for t in teams if str((t or {}).get("homeAway")) == "away"), None)
            if not home or not away:
                continue
            hab = str(((home.get("team") or {}).get("abbreviation")) or "").strip().upper()
            aab = str(((away.get("team") or {}).get("abbreviation")) or "").strip().upper()
            if hab == h and aab == a:
                return str((e or {}).get("id") or "").strip() or None
        except Exception:
            continue
    return None
