"""GENERATED by scripts/port_basketball_orchestrator.py (plan P6, lane basketball-native-orchestrator).

Native port of the definitions production EXECUTES from
  vendor/wnba_betting_repo/src/wnba_betting/sim/connected_game.py (sha256 083a4bd0b509087a...)
checked definition by definition against
  vendor/nba_betting_repo/src/nba_betting/sim/connected_game.py (sha256 ff7ff918bd9467ef...)
Ported: _read_processed_any, _clean_id_str, _espn_name_to_id_map_for_game, _load_lineup_context_tables, _apply_lineup_teammate_effects_to_priors, _norm_player_key.

Mechanical edits: global `paths` / `LEAGUE` reads -> `orch.paths` / `orch.league` (runtime.OrchestratorEnv);
a keyword-only `orch` on every function that needs it, passed at every call; relative imports re-pointed
at this package. Calls to the 29 names Syndicate replaced go to hooks.py.

PARITY: scripts/basketball_orchestrator_parity.py replays recorded REAL production games through this
orchestrator and the vendored one, same seed, and compares every leaf of the output.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple
import numpy as np
import pandas as pd

from .boxscores import _espn_event_id_for_matchup, _espn_summary, _espn_to_tri
from .player_names import normalize_player_name_key


def _read_processed_any(parquet_path, csv_path) -> pd.DataFrame:
    try:
        if parquet_path.exists():
            return pd.read_parquet(parquet_path)
    except Exception:
        pass
    try:
        if csv_path.exists():
            return pd.read_csv(csv_path)
    except Exception:
        pass
    return pd.DataFrame()


def _clean_id_str(x: Any) -> str:
    try:
        s = str(x or "").strip()
        if s.lower() in ("nan", "none"):
            return ""
        if s.endswith(".0") and s[:-2].isdigit():
            s = s[:-2]
        return s
    except Exception:
        return ""


def _espn_name_to_id_map_for_game(
    date_str: str,
    home_tri: str,
    away_tri: str,
    event_id: Optional[str] = None, *, orch,
) -> dict[tuple[str, str], str]:
    """Return mapping (team_tricode, normalized_player_key) -> espn_athlete_id.

    Prefer providing event_id (e.g., from rotation stints) to avoid relying on scoreboard lookup.
    Uses ESPN summary boxscore and normalizes names via _norm_player_key.
    """
    if not str(event_id or "").strip() and not date_str:
        return {}

    def _from_pbp_history(lookback_days: int = 120) -> dict[tuple[str, str], str]:
        """Local fallback mapping from pbp_espn_history.csv substitution rows."""
        try:
            fp = orch.paths.data_processed / "pbp_espn_history.csv"
            if not fp.exists():
                return {}
            usecols = [
                "date",
                "team",
                "enter_player_id",
                "exit_player_id",
                "enter_player_name",
                "exit_player_name",
            ]
            hist = pd.read_csv(fp, usecols=usecols)
            if hist is None or hist.empty:
                return {}

            teams = {str(home_tri or "").upper().strip(), str(away_tri or "").upper().strip()}
            teams = {t for t in teams if t}
            if teams:
                hist["team"] = hist["team"].astype(str).str.upper().str.strip()
                hist = hist[hist["team"].isin(list(teams))].copy()
            if hist.empty:
                return {}

            try:
                cutoff = pd.to_datetime(str(date_str), errors="coerce")
                if pd.notna(cutoff):
                    start = cutoff - pd.Timedelta(days=int(lookback_days))
                    hist["date"] = pd.to_datetime(hist["date"], errors="coerce")
                    hist = hist[(hist["date"].notna()) & (hist["date"] >= start) & (hist["date"] <= cutoff)].copy()
            except Exception:
                pass
            if hist.empty:
                return {}

            def _rows(id_col: str, name_col: str) -> pd.DataFrame:
                try:
                    df = hist[["team", "date", id_col, name_col]].copy()
                    df["id"] = df[id_col].map(_clean_id_str)
                    df["key"] = df[name_col].astype(str).map(_norm_player_key)
                    df = df[(df["id"].astype(str).str.len() > 0) & (df["key"].astype(str).str.len() > 0)].copy()
                    df["team"] = df["team"].astype(str).str.upper().str.strip()
                    df["key"] = df["key"].astype(str).str.upper().str.strip()
                    return df[["team", "key", "id", "date"]]
                except Exception:
                    return pd.DataFrame(columns=["team", "key", "id", "date"])

            a = _rows("enter_player_id", "enter_player_name")
            b = _rows("exit_player_id", "exit_player_name")
            combo = pd.concat([a, b], ignore_index=True)
            if combo.empty:
                return {}

            try:
                combo = combo.sort_values(["date"])
            except Exception:
                pass
            combo = combo.drop_duplicates(subset=["team", "key"], keep="last")

            out: dict[tuple[str, str], str] = {}
            for _, r in combo.iterrows():
                t = str(r.get("team") or "").upper().strip()
                k = str(r.get("key") or "").upper().strip()
                pid = _clean_id_str(r.get("id"))
                if t and k and pid:
                    out[(t, k)] = pid
            return out
        except Exception:
            return {}
    try:
        from .boxscores import _espn_event_id_for_matchup, _espn_summary, _espn_to_tri  # type: ignore
    except Exception:
        return _from_pbp_history()

    try:
        eid = str(event_id or "").strip() or (_espn_event_id_for_matchup(str(date_str), home_tri=str(home_tri), away_tri=str(away_tri), orch=orch) or "")
        if not eid:
            return _from_pbp_history()
        summ = _espn_summary(eid, orch=orch)
        box = (summ or {}).get("boxscore") or {}
        teams = box.get("players") or []
        if not isinstance(teams, list) or not teams:
            return _from_pbp_history()
        out: dict[tuple[str, str], str] = {}
        for tp in teams:
            team = (tp or {}).get("team") or {}
            team_ab = str(team.get("abbreviation") or "").strip().upper()
            team_tri = _espn_to_tri(team_ab, orch=orch) if team_ab else ""
            stats_groups = (tp or {}).get("statistics") or []
            if not isinstance(stats_groups, list) or not stats_groups:
                continue
            g0 = stats_groups[0] or {}
            athletes = g0.get("athletes") or []
            if not isinstance(athletes, list):
                continue
            for a in athletes:
                if not isinstance(a, dict):
                    continue
                athlete = a.get("athlete") or {}
                pid = _clean_id_str(athlete.get("id"))
                name = str(athlete.get("displayName") or "").strip()
                if not pid or not name or not team_tri:
                    continue
                key = _norm_player_key(name)
                if not key:
                    continue
                out[(team_tri, key)] = pid
        return out or _from_pbp_history()
    except Exception:
        return _from_pbp_history()


def _load_lineup_context_tables(*, orch) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Load (baselines_df, teammate_df) if available; else (empty, empty)."""
    base = _read_processed_any(orch.paths.data_processed / "lineup_player_baselines.parquet", orch.paths.data_processed / "lineup_player_baselines.csv")
    tm = _read_processed_any(orch.paths.data_processed / "lineup_teammate_effects.parquet", orch.paths.data_processed / "lineup_teammate_effects.csv")
    if base is None:
        base = pd.DataFrame()
    if tm is None:
        tm = pd.DataFrame()
    return base, tm


def _apply_lineup_teammate_effects_to_priors(
    team_players: pd.DataFrame,
    team_tri: str,
    date_str: Optional[str],
    home_tri: str,
    away_tri: str,
    event_id: Optional[str] = None, *, orch,
) -> pd.DataFrame:
    """Apply minutes-weighted teammate effects as multiplicative adjustments to per-minute priors.

    This is a soft conditioning layer: it nudges rates but stays bounded.
    If required tables or ESPN IDs are unavailable, returns team_players unchanged.
    """
    def _set_diag(df: pd.DataFrame, **kw: Any) -> pd.DataFrame:
        try:
            if isinstance(df, pd.DataFrame):
                d = dict(getattr(df, "attrs", {}).get("_lineup_effects", {}) or {})
                d.update(kw)
                df.attrs["_lineup_effects"] = d
        except Exception:
            pass
        return df

    if team_players is None or team_players.empty:
        return _set_diag(team_players, attempted=True, applied=False, reason="empty_players")
    if not date_str:
        return _set_diag(team_players, attempted=True, applied=False, reason="missing_date")

    base, tm = _load_lineup_context_tables(orch=orch)
    if base.empty or tm.empty:
        return _set_diag(team_players, attempted=True, applied=False, reason="missing_tables")

    needed_cols = {"team", "player_id", "minutes"}
    if not {"team", "player_id"}.issubset(set(base.columns)):
        return _set_diag(team_players, attempted=True, applied=False, reason="bad_baselines_schema")
    if not {"team", "player_id", "teammate_id"}.issubset(set(tm.columns)):
        return _set_diag(team_players, attempted=True, applied=False, reason="bad_teammate_schema")

    # ESPN athlete ID mapping for this matchup
    name_to_id = _espn_name_to_id_map_for_game(str(date_str), home_tri=str(home_tri), away_tri=str(away_tri), event_id=event_id, orch=orch)
    if not name_to_id:
        return _set_diag(team_players, attempted=True, applied=False, reason="no_espn_id_map")

    out = team_players.copy()
    team_u = str(team_tri or "").strip().upper()
    out["_pkey"] = out.get("player_name", pd.Series(["" for _ in range(len(out))])).map(_norm_player_key)
    out["_espn_id"] = out["_pkey"].map(lambda k: name_to_id.get((team_u, k), ""))
    out["_espn_id"] = out["_espn_id"].astype(str).replace({"nan": "", "None": ""}).str.strip()

    mapped_n = int((out["_espn_id"].astype(str).str.len() > 0).sum())

    # Only apply when we have priors.
    prior_stats = [
        "pts",
        "reb",
        "ast",
        "threes",
        "threes_att",
        "tov",
        "stl",
        "blk",
        "fga",
        "fgm",
        "fta",
        "ftm",
        "pf",
    ]
    have_any = any(f"_prior_{s}_pm" in out.columns for s in prior_stats)
    if not have_any:
        return _set_diag(team_players, attempted=True, applied=False, reason="missing_prior_columns", mapped_players=mapped_n)

    # Normalize tables
    try:
        base = base.copy()
        tm = tm.copy()
        base["team"] = base["team"].astype(str).str.upper().str.strip()
        tm["team"] = tm["team"].astype(str).str.upper().str.strip()
        base["player_id"] = base["player_id"].astype(str).str.replace(r"^(\d+)\.0$", r"\1", regex=True).str.strip()
        tm["player_id"] = tm["player_id"].astype(str).str.replace(r"^(\d+)\.0$", r"\1", regex=True).str.strip()
        tm["teammate_id"] = tm["teammate_id"].astype(str).str.replace(r"^(\d+)\.0$", r"\1", regex=True).str.strip()
    except Exception:
        return _set_diag(team_players, attempted=True, applied=False, reason="table_normalization_failed", mapped_players=mapped_n)

    base_t = base[base["team"] == team_u]
    tm_t = tm[tm["team"] == team_u]
    if base_t.empty or tm_t.empty:
        return _set_diag(team_players, attempted=True, applied=False, reason="no_team_rows", mapped_players=mapped_n)

    # Minutes weights from the sim rotation
    mins = pd.to_numeric(out.get("_sim_min"), errors="coerce").fillna(0.0).to_numpy(dtype=float)
    id_list = out["_espn_id"].astype(str).tolist()
    if not any(id_list):
        return _set_diag(team_players, attempted=True, applied=False, reason="no_players_mapped", mapped_players=mapped_n)
    id_to_min = {str(pid): float(mins[i]) for i, pid in enumerate(id_list) if str(pid)}

    # Map stat -> columns in tables
    stat_to_base_per36 = {
        "pts": "pts_per36",
        "reb": "reb_per36",
        "ast": "ast_per36",
        "tov": "tov_per36",
        "stl": "stl_per36",
        "blk": "blk_per36",
        "pf": "pf_per36",
        "fga": "fga_per36",
        "threes_att": "three_pa_per36",
    }
    stat_to_with_per36 = {
        "pts": "pts_per36_with",
        "reb": "reb_per36_with",
        "ast": "ast_per36_with",
        "tov": "tov_per36_with",
        "stl": "stl_per36_with",
        "blk": "blk_per36_with",
        "pf": "pf_per36_with",
        "fga": "fga_per36_with",
        "threes_att": "three_pa_per36_with",
    }
    # For makes, approximate with attempts multiplier.
    make_like = {"fgm": "fga", "ftm": "fta", "threes": "threes_att"}

    # Precompute baseline per36 for each player id.
    base_idx = base_t.set_index("player_id", drop=False)

    # Apply a bounded multiplier per player/stat.
    nudges = 0
    max_abs_mult_delta = 0.0
    for i in range(len(out)):
        pid = str(out.at[i, "_espn_id"] or "").strip()
        if not pid:
            continue
        # Teammates present in this sim rotation
        teammates = [(tid, m) for tid, m in id_to_min.items() if tid and tid != pid and m > 0]
        if not teammates:
            continue

        # Pre-filter teammate rows once
        trows = tm_t[tm_t["player_id"] == pid]
        if trows.empty:
            continue
        trows = trows[trows["teammate_id"].isin([tid for tid, _ in teammates])]
        if trows.empty:
            continue

        for stat in prior_stats:
            prior_col = f"_prior_{stat}_pm"
            if prior_col not in out.columns:
                continue
            # determine baseline/with columns
            if stat in make_like:
                proxy = make_like[stat]
                base_col = stat_to_base_per36.get(proxy)
                with_col = stat_to_with_per36.get(proxy)
            elif stat == "fta":
                # no explicit baseline column; infer via ftm/fta if available is too noisy, so skip
                base_col = None
                with_col = None
            else:
                base_col = stat_to_base_per36.get(stat)
                with_col = stat_to_with_per36.get(stat)

            if not base_col or not with_col:
                continue
            if base_col not in base_idx.columns or with_col not in trows.columns:
                continue

            try:
                base_val = float(pd.to_numeric(base_idx.at[pid, base_col], errors="coerce"))
            except Exception:
                base_val = float("nan")
            if not np.isfinite(base_val) or base_val <= 1e-9:
                continue

            # Weighted mean of (with/base) over expected teammates
            w_sum = 0.0
            r_sum = 0.0
            for tid, w in teammates:
                if w <= 0:
                    continue
                rr = trows[trows["teammate_id"] == tid]
                if rr.empty:
                    continue
                v = pd.to_numeric(rr.iloc[0].get(with_col), errors="coerce")
                v = float(v) if v is not None and np.isfinite(v) else float("nan")
                if not np.isfinite(v):
                    continue
                r = float(v) / float(base_val)
                if not np.isfinite(r):
                    continue
                w_sum += float(w)
                r_sum += float(w) * float(r)
            if w_sum <= 0:
                continue
            mult = float(r_sum / w_sum)
            # Tight caps: we want nudges, not rewrites.
            mult = float(np.clip(mult, 0.85, 1.15))
            if np.isfinite(mult):
                max_abs_mult_delta = max(float(max_abs_mult_delta), float(abs(mult - 1.0)))

            cur = pd.to_numeric(out.at[i, prior_col], errors="coerce")
            cur = float(cur) if cur is not None and np.isfinite(cur) else None
            if cur is None:
                continue
            new_v = float(max(0.0, cur * mult))
            if abs(new_v - cur) > 1e-12:
                nudges += 1
            out.at[i, prior_col] = new_v

    out = out.drop(columns=[c for c in ["_pkey"] if c in out.columns])
    return _set_diag(out, attempted=True, applied=(nudges > 0), mapped_players=mapped_n, nudges=int(nudges), max_abs_mult_delta=float(max_abs_mult_delta))


def _norm_player_key(x: Any) -> str:
    return normalize_player_name_key(x, case="upper")
