"""GENERATED by scripts/port_basketball_orchestrator.py (plan P6, lane basketball-native-orchestrator).

Native port of the definitions production EXECUTES from
  vendor/wnba_betting_repo/src/wnba_betting/player_priors.py (sha256 4915cab850cb3d39...)
checked definition by definition against
  vendor/nba_betting_repo/src/nba_betting/player_priors.py (sha256 8a4c2795b3d277b1...)
Ported: _norm_player_key.

Mechanical edits: global `paths` / `LEAGUE` reads -> `orch.paths` / `orch.league` (runtime.OrchestratorEnv);
a keyword-only `orch` on every function that needs it, passed at every call; relative imports re-pointed
at this package. Calls to the 29 names Syndicate replaced go to hooks.py.

PARITY: scripts/basketball_orchestrator_parity.py replays recorded REAL production games through this
orchestrator and the vendored one, same seed, and compares every leaf of the output.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Iterable, Optional, Tuple
import numpy as np
import pandas as pd

from .player_names import normalize_player_name_key


def _norm_player_key(x: Any) -> str:
    return normalize_player_name_key(x, case="upper")
