"""GENERATED by scripts/port_basketball_orchestrator.py (plan P6, lane basketball-native-orchestrator).

Native port of the definitions production EXECUTES from
  vendor/wnba_betting_repo/src/wnba_betting/player_names.py (sha256 51e1abd4713d2246...)
checked definition by definition against
  vendor/nba_betting_repo/src/nba_betting/player_names.py (sha256 51e1abd4713d2246...)
Ported: _SUFFIX_TOKENS, _CANONICAL_PLAYER_NAME_ALIASES, normalize_player_name_key.

Mechanical edits: global `paths` / `LEAGUE` reads -> `orch.paths` / `orch.league` (runtime.OrchestratorEnv);
a keyword-only `orch` on every function that needs it, passed at every call; relative imports re-pointed
at this package. Calls to the 29 names Syndicate replaced go to hooks.py.

PARITY: scripts/basketball_orchestrator_parity.py replays recorded REAL production games through this
orchestrator and the vendored one, same seed, and compares every leaf of the output.
"""

from __future__ import annotations

from typing import Any
import unicodedata


_SUFFIX_TOKENS = frozenset({"JR", "SR", "II", "III", "IV", "V"})


_CANONICAL_PLAYER_NAME_ALIASES = {
    "CARLTON CARRINGTON": "BUB CARRINGTON",
    "CAM PAYNE": "CAMERON PAYNE",
    "HERB JONES": "HERBERT JONES",
    "MOE WAGNER": "MORITZ WAGNER",
    "NIC CLAXTON": "NICOLAS CLAXTON",
    "RON HOLLAND": "RONALD HOLLAND",
}


def normalize_player_name_key(value: Any, *, case: str = "upper") -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    if "(" in text:
        text = text.split("(", 1)[0]
    text = text.replace("-", " ")
    text = text.replace(".", "").replace("'", "").replace(",", " ")
    text = " ".join(text.split())
    if not text:
        return ""
    try:
        text = unicodedata.normalize("NFKD", text)
        text = "".join(ch for ch in text if not unicodedata.combining(ch))
        text = text.encode("ascii", "ignore").decode("ascii")
    except Exception:
        pass
    tokens = [token for token in text.upper().split() if token not in _SUFFIX_TOKENS]
    if not tokens:
        return ""
    normalized = " ".join(tokens)
    normalized = _CANONICAL_PLAYER_NAME_ALIASES.get(normalized, normalized)
    if case == "lower":
        return normalized.lower()
    return normalized
