"""GENERATED by scripts/port_basketball_orchestrator.py (plan P6, lane basketball-native-orchestrator).

Native port of the definitions production EXECUTES from
  vendor/wnba_betting_repo/src/wnba_betting/prob_calibration.py (sha256 cb6058a6bee500ab...)
checked definition by definition against
  vendor/nba_betting_repo/src/nba_betting/prob_calibration.py (sha256 cb6058a6bee500ab...)
Ported: _PROB_CALIBRATION_INDEX, _PROB_CALIBRATION_CACHE, _calibration_period_prob_paths, _clamp01, _load_prob_calibration_for_date, calibrate_prob.

Anchored edits:
  * _PROB_CALIBRATION_INDEX: one index per data root (the vendored global assumed one root per process)
  * _PROB_CALIBRATION_CACHE: keyed by (data root, date)
  * _load_prob_calibration_for_date: cache key includes the data root
  * _load_prob_calibration_for_date: per-root index
  * _load_prob_calibration_for_date: per-root index
  * _load_prob_calibration_for_date: per-root index
  * _calibration_period_prob_paths: the vendored repo tree (vendor/<pkg>_repo/data/processed) is no longer read. Measured 2026-10-09 on the fleet: it holds 0 calibration_period_probs_*.json for either league

Mechanical edits: global `paths` / `LEAGUE` reads -> `orch.paths` / `orch.league` (runtime.OrchestratorEnv);
a keyword-only `orch` on every function that needs it, passed at every call; relative imports re-pointed
at this package. Calls to the 29 names Syndicate replaced go to hooks.py.

PARITY: scripts/basketball_orchestrator_parity.py replays recorded REAL production games through this
orchestrator and the vendored one, same seed, and compares every leaf of the output.
"""

from __future__ import annotations

import json
from typing import Any, Optional
import numpy as np
import pandas as pd


_PROB_CALIBRATION_INDEX: dict[Any, list[tuple[pd.Timestamp, Any]]] = {}


_PROB_CALIBRATION_CACHE: dict[tuple[Any, str], Optional[dict[str, Any]]] = {}


def _calibration_period_prob_paths(*, orch) -> list[Any]:
    """Return calibration artifacts with repo copies preferred over active data root."""
    chosen: dict[pd.Timestamp, Any] = {}
    roots = [orch.paths.data_processed]
    for root in roots:
        try:
            for fp in root.glob("calibration_period_probs_*.json"):
                ds = fp.name.replace("calibration_period_probs_", "").replace(".json", "")
                try:
                    dt = pd.to_datetime(ds).normalize()
                except Exception:
                    continue
                if dt not in chosen:
                    chosen[dt] = fp
        except Exception:
            continue
    return [chosen[dt] for dt in sorted(chosen.keys())]


def _clamp01(x: Any, default: float = 0.5) -> float:
    try:
        v = float(x)
        if not np.isfinite(v):
            return float(default)
        return float(max(0.0, min(1.0, v)))
    except Exception:
        return float(default)


def _load_prob_calibration_for_date(date_str: str, *, orch) -> Optional[dict[str, Any]]:
    """Load the most recent period probability calibration JSON on/before (date-1).

    Looks for data/processed/calibration_period_probs_YYYY-MM-DD.json.

    Returns the JSON object (dict) or None.
    """
    try:
        target = pd.to_datetime(date_str).normalize()
    except Exception:
        return None

    key = (orch.paths, str(target.date()))
    if key in _PROB_CALIBRATION_CACHE:
        return _PROB_CALIBRATION_CACHE[key]

    cutoff = target - pd.Timedelta(days=1)

    if _PROB_CALIBRATION_INDEX.get(orch.paths) is None:
        idx: list[tuple[pd.Timestamp, Any]] = []
        try:
            for fp in _calibration_period_prob_paths(orch=orch):
                ds = fp.name.replace("calibration_period_probs_", "").replace(".json", "")
                try:
                    dt = pd.to_datetime(ds).normalize()
                except Exception:
                    continue
                idx.append((dt, fp))
        except Exception:
            idx = []
        _PROB_CALIBRATION_INDEX[orch.paths] = sorted(idx, key=lambda t: t[0])

    best_fp = None
    try:
        for dt, fp in _PROB_CALIBRATION_INDEX.get(orch.paths) or []:
            if dt <= cutoff:
                best_fp = fp
            else:
                break
    except Exception:
        best_fp = None

    if best_fp is None:
        _PROB_CALIBRATION_CACHE[key] = None
        return None

    try:
        obj = json.loads(best_fp.read_text(encoding="utf-8"))
        _PROB_CALIBRATION_CACHE[key] = obj if isinstance(obj, dict) else None
        return _PROB_CALIBRATION_CACHE[key]
    except Exception:
        _PROB_CALIBRATION_CACHE[key] = None
        return None


def calibrate_prob(date_str: str, market: str, p: float, *, orch) -> float:
    """Calibrate a raw probability using the latest available calibration artifact.

    Args:
        date_str: slate date (YYYY-MM-DD). Calibration uses <= date-1.
        market: market key, e.g. "q1_over", "h1_over".
        p: raw probability in [0,1].

    Returns:
        Calibrated probability in [0,1]. Falls back to raw if no calibration.
    """
    p = _clamp01(p, default=0.5)
    cal = _load_prob_calibration_for_date(date_str, orch=orch) or {}
    markets = cal.get("markets") if isinstance(cal, dict) else None
    if not isinstance(markets, dict):
        return p

    m = markets.get(str(market))
    if not isinstance(m, dict):
        return p

    edges = m.get("bin_edges")
    vals = m.get("p_cal")
    n_bin = m.get("n_bin")
    if not isinstance(edges, list) or not isinstance(vals, list) or len(edges) < 2 or len(vals) < 1:
        return p

    try:
        e = np.asarray(edges, dtype=float)
        v = np.asarray(vals, dtype=float)
        nb = np.asarray(n_bin, dtype=float) if isinstance(n_bin, list) else None
        e = e[np.isfinite(e)]
        v = v[np.isfinite(v)]
        if e.size < 2 or v.size < 1:
            return p

        # bins are [e[i], e[i+1]) except last which includes 1.0
        idx = int(np.digitize([p], e[1:-1], right=False)[0])
        idx = max(0, min(idx, int(v.size - 1)))
        p_cal = _clamp01(float(v[idx]), default=p)

        # Blend calibrated probability toward raw when sample size is small.
        # This limits overfitting, especially in narrow windows.
        # Weight grows with per-bin sample size.
        try:
            if nb is None or nb.size == 0:
                return p_cal
            n_here = float(nb[min(idx, int(nb.size - 1))])
            prior = 25.0
            w = float(n_here / (n_here + prior)) if (n_here >= 0.0) else 0.0
            w = float(max(0.0, min(1.0, w)))
            return _clamp01(((1.0 - w) * p) + (w * p_cal), default=p)
        except Exception:
            return p_cal
    except Exception:
        return p
