"""GENERATED by scripts/port_basketball_orchestrator.py (plan P6, lane basketball-native-orchestrator).

Native port of the definitions production EXECUTES from
  vendor/wnba_betting_repo/src/wnba_betting/prop_ladders.py (sha256 35d478ced2751ff4...)
checked definition by definition against
  vendor/nba_betting_repo/src/nba_betting/prop_ladders.py (sha256 35d478ced2751ff4...)
Ported: _safe_float, _safe_int, _rounded_count_map, _distribution_count_map, build_exact_distribution_payload, build_exact_ladder_payload_from_distribution, build_exact_ladder_payload.

Mechanical edits: global `paths` / `LEAGUE` reads -> `orch.paths` / `orch.league` (runtime.OrchestratorEnv);
a keyword-only `orch` on every function that needs it, passed at every call; relative imports re-pointed
at this package. Calls to the 29 names Syndicate replaced go to hooks.py.

PARITY: scripts/basketball_orchestrator_parity.py replays recorded REAL production games through this
orchestrator and the vendored one, same seed, and compares every leaf of the output.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Sequence
import numpy as np


def _safe_float(value: Any) -> float | None:
    try:
        if value is None:
            return None
        return float(value)
    except Exception:
        return None


def _safe_int(value: Any) -> int | None:
    try:
        if value is None:
            return None
        return int(float(value))
    except Exception:
        return None


def _rounded_count_map(values: Sequence[Any]) -> dict[int, int]:
    arr = np.asarray(values, dtype=float)
    if not arr.size:
        return {}
    arr = arr[np.isfinite(arr)]
    if not arr.size:
        return {}

    rounded = np.rint(arr).astype(int)
    totals, counts = np.unique(rounded, return_counts=True)
    return {int(total): int(count) for total, count in zip(totals.tolist(), counts.tolist())}


def _distribution_count_map(raw_distribution: Any) -> dict[int, int]:
    if not isinstance(raw_distribution, dict):
        return {}

    count_map: dict[int, int] = {}
    for raw_total, raw_count in raw_distribution.items():
        total = _safe_int(raw_total)
        count = _safe_int(raw_count)
        if total is None or count is None or count <= 0:
            continue
        count_map[int(total)] = int(count)
    return count_map


def build_exact_distribution_payload(values: Sequence[Any]) -> dict[str, int] | None:
    count_map = _rounded_count_map(values)
    if not count_map:
        return None
    return {str(total): int(count) for total, count in sorted(count_map.items())}


def build_exact_ladder_payload_from_distribution(
    raw_distribution: Any,
    *,
    mean_value: Any = None,
) -> dict[str, Any] | None:
    count_map = _distribution_count_map(raw_distribution)
    if not count_map:
        return None

    sim_count = int(sum(count_map.values()))
    max_count = max(count_map.values()) if count_map else 0
    mode_candidates = sorted(total for total, count in count_map.items() if count == max_count)
    mode_total = mode_candidates[len(mode_candidates) // 2] if mode_candidates else None

    mean_num = _safe_float(mean_value)
    if mean_num is None or not np.isfinite(mean_num):
        weighted_sum = float(sum(float(total) * float(count) for total, count in count_map.items()))
        mean_num = float(weighted_sum / float(max(1, sim_count)))

    running = 0
    rows_desc: list[dict[str, Any]] = []
    for total in sorted(count_map.keys(), reverse=True):
        exact_count = int(count_map.get(total, 0))
        running += exact_count
        rows_desc.append(
            {
                "total": int(total),
                "hitCount": int(running),
                "hitProb": float(running) / float(max(1, sim_count)),
                "exactCount": int(exact_count),
                "exactProb": float(exact_count) / float(max(1, sim_count)),
            }
        )
    rows_desc.reverse()

    return {
        "simCount": int(sim_count),
        "mean": float(mean_num),
        "mode": int(mode_total) if mode_total is not None else None,
        "modeProb": (float(max_count) / float(max(1, sim_count))) if max_count else None,
        "minTotal": int(min(count_map.keys())),
        "maxTotal": int(max(count_map.keys())),
        "distribution": {str(total): int(count) for total, count in sorted(count_map.items())},
        "ladder": rows_desc,
        "ladderShape": "exact",
    }


def build_exact_ladder_payload(values: Sequence[Any]) -> dict[str, Any] | None:
    if values is None:
        return None
    arr = np.asarray(values, dtype=float)
    if not arr.size:
        return None
    arr = arr[np.isfinite(arr)]
    if not arr.size:
        return None

    return build_exact_ladder_payload_from_distribution(
        build_exact_distribution_payload(arr),
        mean_value=float(np.mean(arr)),
    )
