"""GENERATED by scripts/port_basketball_orchestrator.py (plan P6, lane basketball-native-orchestrator).

Native port of the definitions production EXECUTES from
  vendor/wnba_betting_repo/src/wnba_betting/sim/quarters.py (sha256 82f6f6d299e43fd1...)
checked definition by definition against
  vendor/nba_betting_repo/src/nba_betting/sim/quarters.py (sha256 e9eab152965a7140...)
Ported: TeamContext, GameInputs, QuarterResult, sample_quarter_scores.

Mechanical edits: global `paths` / `LEAGUE` reads -> `orch.paths` / `orch.league` (runtime.OrchestratorEnv);
a keyword-only `orch` on every function that needs it, passed at every call; relative imports re-pointed
at this package. Calls to the 29 names Syndicate replaced go to hooks.py.

PARITY: scripts/basketball_orchestrator_parity.py replays recorded REAL production games through this
orchestrator and the vendored one, same seed, and compares every leaf of the output.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple
import numpy as np
import pandas as pd


@dataclass
class TeamContext:
    team: str
    pace: float  # possessions per game
    off_rating: float  # points per 100 possessions
    def_rating: float  # points allowed per 100 possessions
    injuries_out: int = 0
    back_to_back: bool = False
    # Pregame-known schedule context. Convention: 0 means played yesterday (B2B),
    # 1 means played 2 days ago, 2 means played 3 days ago, 3 means 4+ days rest.
    rest_days: Optional[int] = None
    # Additional schedule density signal (pregame-known): number of games played in
    # the last 3 days (excluding today). Range typically 0..3.
    games_last_3d: Optional[int] = None
    form_7: Optional[float] = None  # recent offense performance delta
    form_30: Optional[float] = None


@dataclass
class GameInputs:
    date: str
    home: TeamContext
    away: TeamContext
    market_total: Optional[float] = None
    market_home_spread: Optional[float] = None
    # Optional tuned blend weights. If None, defaults can be loaded from
    # data/processed/quarters_blend_weights.json.
    blend_total_market_w: Optional[float] = None
    blend_margin_market_w: Optional[float] = None


@dataclass
class QuarterResult:
    q: int
    home_pts_mu: float
    home_pts_sigma: float
    away_pts_mu: float
    away_pts_sigma: float
    corr: float  # correlation between home/away scoring in the quarter


def sample_quarter_scores(
    quarters: List[QuarterResult],
    n_samples: int = 2000,
    rng: Optional[np.random.Generator] = None,
    round_to_int: bool = True,
) -> Tuple[np.ndarray, np.ndarray]:
    """Sample per-quarter home/away points from QuarterResult parameters.

    Returns:
      home_q, away_q: arrays of shape (n_samples, n_quarters)
    """
    if rng is None:
        rng = np.random.default_rng()
    n = int(max(1, n_samples))
    qs = list(quarters or [])
    k = len(qs)
    if k == 0:
        return np.zeros((n, 0)), np.zeros((n, 0))

    home_out = np.zeros((n, k), dtype=float)
    away_out = np.zeros((n, k), dtype=float)
    for j, q in enumerate(qs):
        mu = np.array([float(q.home_pts_mu), float(q.away_pts_mu)], dtype=float)
        sh = float(q.home_pts_sigma)
        sa = float(q.away_pts_sigma)
        corr = float(getattr(q, "corr", 0.0) or 0.0)
        corr = float(max(-0.75, min(0.75, corr)))
        cov = np.array(
            [[sh**2, corr * sh * sa], [corr * sh * sa, sa**2]],
            dtype=float,
        )
        try:
            L = np.linalg.cholesky(cov)
            z = rng.normal(size=(n, 2))
            v = z @ L.T
            x = mu[None, :] + v
        except Exception:
            x = rng.normal(loc=mu[None, :], scale=np.array([sh, sa])[None, :], size=(n, 2))
        x = np.maximum(0.0, x)
        home_out[:, j] = x[:, 0]
        away_out[:, j] = x[:, 1]

    if round_to_int:
        home_out = np.maximum(0, np.rint(home_out)).astype(int)
        away_out = np.maximum(0, np.rint(away_out)).astype(int)
    return home_out, away_out
