"""GENERATED by scripts/port_basketball_orchestrator.py (plan P6, lane basketball-native-orchestrator).

Native port of the definitions production EXECUTES from
  vendor/wnba_betting_repo/src/wnba_betting/roster_files.py (sha256 16eb4dd408e84550...)
checked definition by definition against
  vendor/nba_betting_repo/src/nba_betting/roster_files.py (sha256 07a8e358984d0a07...)
Ported: roster_file_team_set, roster_file_team_count, pick_rosters_file.

Mechanical edits: global `paths` / `LEAGUE` reads -> `orch.paths` / `orch.league` (runtime.OrchestratorEnv);
a keyword-only `orch` on every function that needs it, passed at every call; relative imports re-pointed
at this package. Calls to the 29 names Syndicate replaced go to hooks.py.

PARITY: scripts/basketball_orchestrator_parity.py replays recorded REAL production games through this
orchestrator and the vendored one, same seed, and compares every leaf of the output.
"""

from __future__ import annotations

from pathlib import Path
import pandas as pd


def roster_file_team_set(path: Path | str | None) -> set[str]:
    if path is None:
        return set()
    try:
        roster_path = Path(path)
    except Exception:
        return set()
    try:
        if not roster_path.exists():
            return set()
        df = pd.read_csv(roster_path, usecols=["TEAM_ABBREVIATION"])
        if not isinstance(df, pd.DataFrame) or df.empty:
            return set()
        vals = df["TEAM_ABBREVIATION"].dropna().astype(str).str.upper().str.strip()
        return {v for v in vals.tolist() if v}
    except Exception:
        return set()


def roster_file_team_count(path: Path | str | None) -> int:
    return int(len(roster_file_team_set(path)))


def pick_rosters_file(processed_dir: Path | str, season: str | None = None) -> Path | None:
    processed = Path(processed_dir)
    candidates: list[Path] = []
    seen: set[Path] = set()

    def _add(path: Path) -> None:
        if path.exists() and path not in seen:
            seen.add(path)
            candidates.append(path)

    if season:
        _add(processed / f"rosters_{season}.csv")
        start_year = str(season).split("-", 1)[0].strip()
        if start_year:
            _add(processed / f"rosters_{start_year}.csv")
            for path in sorted(processed.glob(f"rosters_{start_year}*.csv")):
                _add(path)

    if not candidates:
        for path in sorted(processed.glob("rosters_*.csv")):
            _add(path)

    if not candidates:
        return None

    candidates.sort(
        key=lambda p: (roster_file_team_count(p), p.stat().st_mtime if p.exists() else 0),
        reverse=True,
    )
    return candidates[0]
