"""GENERATED by scripts/port_basketball_orchestrator.py, PASS 2: the WNBA fork's TEAM_TRICODES
(vendor/wnba_betting_repo/src/wnba_betting/teams.py, sha256 605edb6960731182...), by value.
"""

_NAME_TO_TRI = {
    "Atlanta Dream": "ATL",
    "Chicago Sky": "CHI",
    "Connecticut Sun": "CON",
    "Dallas Wings": "DAL",
    "Golden State Valkyries": "GSV",
    "Indiana Fever": "IND",
    "Las Vegas Aces": "LVA",
    "Los Angeles Sparks": "LAS",
    "Minnesota Lynx": "MIN",
    "New York Liberty": "NYL",
    "Phoenix Mercury": "PHX",
    "Portland Fire": "POR",
    "Seattle Storm": "SEA",
    "Toronto Tempo": "TOR",
    "Washington Mystics": "WSH",
}

TEAM_TRICODES = tuple(sorted(set(_NAME_TO_TRI.values())))
