"""`#621` Phase 4 -- `_sim_many` itself emits the joint, on BOTH execution paths.

The unit tests around `JointAccumulator` prove the container works. They cannot
prove the producer is WIRED, and the standard is explicit that a passing unit
test over a fixture cannot detect an unfed production field. These tests call
the real `_sim_many` over real roster objects and read `out["joint"]`.

BOTH PATHS, DELIBERATELY. `_sim_many` branches on `workers > 1 and total_sims >
1`: above it the four-process `_simw_chunk` path, below it a serial loop. They
are separate copies of the accumulation and **`--workers` defaults to 4**, so a
test that only exercised `workers=1` would be testing the path production does
not take. The drift between those copies is `#334`/`#429`, and it has happened
three times in this file.
"""
from __future__ import annotations

import os
import sys

import pytest

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_REPO, "vendor", "mlb_bettingv2"))
sys.path.insert(0, os.path.join(_REPO, "vendor", "mlb_bettingv2", "tools"))

from sim_engine.joint_outcomes import hitter_label, lookup  # noqa: E402
from sim_engine.models import (  # noqa: E402
    BatterProfile,
    Handedness,
    Lineup,
    ManagerProfile,
    PitcherProfile,
    Player,
    Team,
    TeamRoster,
)


def _player(pid: int, name: str) -> Player:
    return Player(
        mlbam_id=pid,
        full_name=name,
        primary_position="OF",
        bat_side=Handedness.R,
        throw_side=Handedness.R,
    )


def _roster(team_id: int, abbr: str, base_pid: int) -> TeamRoster:
    batters = []
    for slot in range(9):
        pid = base_pid + slot
        prof = BatterProfile(player=_player(pid, f"{abbr} Batter {slot}"))
        # A POWER GRADIENT across the lineup, so the joint has something real to
        # find: slot 0 homers often, slot 8 almost never. A lineup of identical
        # batters would yield nine identical coefficients and could not tell a
        # working measurement from a constant.
        prof.hr_rate = 0.075 - 0.007 * slot
        prof.k_rate = 0.18 + 0.01 * slot
        prof.inplay_hit_rate = 0.30
        batters.append(prof)
    starter = PitcherProfile(player=_player(base_pid + 50, f"{abbr} Starter"))
    starter.role = "SP"
    bullpen = []
    for idx in range(4):
        arm = PitcherProfile(player=_player(base_pid + 60 + idx, f"{abbr} Arm {idx}"))
        arm.role = "RP"
        bullpen.append(arm)
    return TeamRoster(
        team=Team(team_id=team_id, name=abbr, abbreviation=abbr),
        manager=ManagerProfile(),
        lineup=Lineup(batters=batters, pitcher=starter, bench=[], bullpen=bullpen),
    )


@pytest.fixture(scope="module")
def rosters():
    return _roster(1, "AWY", 100), _roster(2, "HOM", 200)


def _sim_many(**kwargs):
    from daily_update import _sim_many as real

    return real(**kwargs)


def _run(rosters, *, sims: int, workers: int):
    away, home = rosters
    return _sim_many(
        away_roster=away,
        home_roster=home,
        sims=sims,
        seed=4242,
        workers=workers,
        hitter_props_top_n=24,
    )


# --- the joint is EMITTED, on the path production actually takes -------------


def test_serial_path_emits_a_joint(rosters):
    out = _run(rosters, sims=120, workers=1)
    joint = out.get("joint")
    assert joint, "workers=1 produced no joint at all"
    assert joint["n"] == 120
    assert joint["method"] == "spearman_rank"
    assert len(joint["labels"]) >= 8 + 18 * 5
    assert len(joint["corr_lower"]) == len(joint["labels"]) * (len(joint["labels"]) - 1) // 2
    assert joint["clamped"] == 0


def test_multiprocessing_path_emits_a_joint_of_the_SAME_shape(rosters):
    """`--workers` DEFAULTS TO 4. This is the production path.

    Before this change `_merge_seg` merged counts only, so nothing joint crossed
    the process boundary -- a producer wired only into the serial loop would
    have shipped completely inert on every real run while passing every test
    above.
    """
    out = _run(rosters, sims=120, workers=4)
    joint = out.get("joint")
    assert joint, "workers=4 produced no joint -- the merge is missing"
    assert joint["n"] == 120, f"chunks did not all arrive: n={joint['n']}"
    serial = _run(rosters, sims=120, workers=1)["joint"]
    assert joint["labels"] == serial["labels"]
    assert len(joint["corr_lower"]) == len(serial["corr_lower"])


def test_home_runs_and_total_bases_are_POSITIVELY_correlated_per_batter(rosters):
    """The load-bearing measurement, as an assertion.

    A home run contributes 4 total bases in the same plate appearance, so this
    correlation is generated by the sim's own structure and must be positive and
    substantial for every batter with a live HR rate. A run where it came back
    near zero would mean the columns are misaligned -- the failure mode that
    concatenating two chunks with mismatched labels would produce.
    """
    joint = _run(rosters, sims=400, workers=1)["joint"]
    values = []
    for pid in list(range(100, 109)) + list(range(200, 209)):
        rho = lookup(joint, hitter_label(pid, "home_runs"), hitter_label(pid, "total_bases"))
        if rho is not None:
            values.append(rho)
    assert len(values) >= 16, f"only {len(values)} batters had a defined coefficient"
    assert min(values) > 0.15, f"min {min(values)} -- columns may be misaligned"
    assert sum(values) / len(values) > 0.40


def test_hits_and_total_bases_are_MORE_correlated_than_home_runs_and_total_bases(rosters):
    """An ORDERING the sim's structure forces, so it catches a subtler
    misalignment than a sign check: total bases follow hits far more closely
    than they follow home runs, because most total bases come from singles."""
    joint = _run(rosters, sims=400, workers=1)["joint"]
    pid = 100
    hits_tb = lookup(joint, hitter_label(pid, "hits"), hitter_label(pid, "total_bases"))
    hr_tb = lookup(joint, hitter_label(pid, "home_runs"), hitter_label(pid, "total_bases"))
    assert hits_tb is not None and hr_tb is not None
    assert hits_tb > hr_tb, (hits_tb, hr_tb)


def test_strikeouts_is_a_LIVE_joint_dimension_not_a_constant_column(rosters):
    """Second witness for lane `mlb-hitter-so-dead-field`'s fix.

    `"SO": so` landed at both sites. If it had NOT, this column would be
    constant across all sims and every correlation touching it would be
    UNDEFINED -- so a defined, negative `hits x strikeouts` is independent
    evidence that the key is live, measured over the whole lineup rather than
    one hitter's histogram.
    """
    joint = _run(rosters, sims=400, workers=1)["joint"]
    defined = []
    for pid in list(range(100, 109)) + list(range(200, 209)):
        rho = lookup(joint, hitter_label(pid, "hits"), hitter_label(pid, "strikeouts"))
        if rho is not None:
            defined.append(rho)
    assert len(defined) >= 16, (
        f"only {len(defined)} strikeout coefficients defined -- if 0, the SO key "
        "is absent again and strikeouts_dist is back to {0: n_sims}"
    )
    # More strikeouts means fewer balls in play, so fewer hits.
    assert sum(defined) / len(defined) < 0.0, sum(defined) / len(defined)


def test_a_sim_with_no_batters_omits_joint_rather_than_publishing_an_empty_one(rosters):
    """Absent must be distinguishable from 'measured, nothing there'."""
    away, home = rosters
    out = _sim_many(
        away_roster=away,
        home_roster=home,
        sims=20,
        seed=1,
        workers=1,
        hitter_hr_top_n=0,
        hitter_props_top_n=0,
    )
    joint = out.get("joint")
    if joint is not None:
        assert joint["labels"], "an EMPTY joint was published -- absent must mean absent"


def test_joint_does_not_disturb_the_marginals_it_sits_beside(rosters):
    """A joint is an ADDITION. Adding it must not move a single existing number."""
    out = _run(rosters, sims=120, workers=1)
    assert out["sims"] == 120
    for segment in ("full", "first1", "first3", "first5"):
        seg = out["segments"][segment]
        assert 0.0 <= seg["home_win_prob"] <= 1.0
        assert len(seg["samples"]) == 50
        assert sum(seg["total_runs_dist"].values()) == 120
    assert "aggregate_boxscore" in out
