"""Syndicate's basketball possession engine: ONE league-parametric engine (nba, wnba; ncaab hooks).

Ported 2026-10-09 (lane basketball-native-engine, plan P1:
docs/ai_context/basketball_live_native_plan.md) from
vendor/nba_betting_repo/src/nba_betting/sim/events.py (and its WNBA twin),
which this module REPLACES at runtime. Generated by
scripts/port_basketball_engine.py; the loop body is the vendored text.

What changed against the vendored engines, and nothing else:
  * The module-level switches (SHOOTER_FT_RATE, BLOCK_MODE, ...) and the WNBA
    ``LEAGUE`` constants are ``LeagueParams`` fields (``league.py``). Inside the
    simulators they bind to the SAME local names, so the per-possession code is
    the vendored code.
  * Lineup sampling is the ``sample_lineup`` PARAMETER. Syndicate used to patch
    the vendored module's ``_sample_lineup`` global for the duration of a call.
  * ``simulate_pbp_game_boxscore`` takes ``state=GameState(...)`` and resumes
    from a live situation (``resume.py``). ``GameState()`` is the opening tip:
    the same draws and the same output as the pregame run.
  * The period count is a parameter (2 halves for NCAAB), and every
    quarter-shaped rule is written in terms of halves, which reduces to the
    old (1, 3) / (2, 4) / 4 for quarters.

PARITY: scripts/basketball_engine_parity.py replays a recorded corpus of REAL
production per-draw inputs through this engine and through the vendored one,
seed for seed. The switch in basketball_props_smart_sim.py was gated on 0
mismatches.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import partial
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from .league import LeagueParams
from .resume import GameState, _fouled_out_names

@dataclass
class EventSimConfig:
    # Pace / possession controls
    possessions_per_game: float = 98.0
    possessions_jitter: float = 0.06  # stddev fraction applied per quarter
    # Scenario-calibration levers (Syndicate lane basketball-scenario-calibration, 2026-10-07). Defaults are the
    # values that were hardcoded before, so an unset config is byte-identical (same RNG draws, same order).
    possession_alternation: float = 0.85  # P(next possession switches team); else a coin flip
    env_sd_scale: float = 0.65  # scale of the per-quarter environment random draw
    # When a points TARGET is given, whether the team-quality prior (team_adj eff_mult) is multiplied on top of the
    # target calibration. The targets are market-anchored (margin 95%), so they already price team quality; the
    # WNBA engine turned this off on 2026-10-01 (TEAM_PRIOR_STACKS_ON_TARGET). True = today's NBA behaviour.
    team_prior_stacks_on_target: bool = True
    # Late-game catch-up / score effects (lane basketball-scenario-calibration, Phase 2 #2, pre-registered 10da26d5;
    # LOAN from basketball-native-engine). Each shot's make probability (and the shooter's FT%) is multiplied by
    # clip(1 - k * dev, 0.85, 1.15), dev = the offense's lead now minus its expected lead to date (target margin x share
    # of regulation elapsed). Real games revert (line-adjusted H2-on-H1 margin slope -0.17); the sim's halves were
    # independent (0.00). 0.0 = off: the factor is exactly 1.0 and no RNG draw is made, so output is byte-identical.
    score_effect_k: float = 0.0

    # Outcome priors (fallbacks when player priors are missing)
    base_tov_per_poss: float = 0.125
    base_shooting_foul_per_fga: float = 0.095
    base_nonshooting_foul_per_poss: float = 0.05
    base_oreb_rate: float = 0.24

    # Defense event rates (fallbacks)
    base_steal_share_of_tov: float = 0.55
    base_block_rate_on_2pa: float = 0.05

    # Blowout / gameflow
    blowout_margin: int = 18
    blowout_q4_margin: int = 15
    garbage_time_pace_scale: float = 0.94
    garbage_time_eff_scale: float = 0.96
    bench_weight_boost: float = 1.35

    # Reconciliation strength
    reconcile_points: bool = True
    reconcile_max_changes_per_quarter: int = 12

    # Debug/diagnostics
    # Recording per-event dictionaries is expensive for large n_sims; keep off by default.
    record_events: bool = False


def _safe_series(df: pd.DataFrame, col: str) -> pd.Series:
    if df is None or df.empty or col not in df.columns:
        return pd.Series([0.0] * (0 if df is None else len(df)), dtype=float)
    return pd.to_numeric(df[col], errors="coerce").fillna(0.0)


def _pick_weighted(rng: np.random.Generator, items: List[Any], weights: np.ndarray) -> Any:
    if not items:
        return None
    w = np.asarray(weights, dtype=float)
    if w.size != len(items):
        w = np.ones(len(items), dtype=float)
    w = np.maximum(0.0, w)
    s = float(np.sum(w))
    if not np.isfinite(s) or s <= 0:
        p = np.full(len(items), 1.0 / len(items))
    else:
        p = w / s
    idx = int(rng.choice(len(items), p=p))
    return items[idx]


def sample_lineup_minutes_weighted(
    rng: np.random.Generator,
    players: pd.DataFrame,
    minutes_weights: np.ndarray,
    k: int = 5,
    blowout_boost_bench: bool = False,
    bench_boost: float = 1.35,
) -> List[int]:
    """Return indices into players of a sampled on-court 5-man unit."""
    n = int(len(players))
    if n <= 0:
        return []
    w = np.asarray(minutes_weights, dtype=float)
    if w.size != n:
        w = np.ones(n, dtype=float)
    w = np.maximum(0.0, w)

    # Bench boost: slightly de-emphasize top-minute guys
    if blowout_boost_bench and n >= 8:
        order = np.argsort(-w)
        top = order[:5]
        rest = order[5:]
        w[top] = w[top] / max(1.0, bench_boost)
        w[rest] = w[rest] * bench_boost

    # Sample without replacement, but be robust if weights degenerate
    s = float(np.sum(w))
    if not np.isfinite(s) or s <= 0:
        probs = np.full(n, 1.0 / n)
    else:
        probs = w / s

    k_eff = int(min(k, n))
    try:
        idx = rng.choice(n, size=k_eff, replace=False, p=probs)
        return [int(i) for i in idx]
    except Exception:
        # Fallback: take top-k by minutes
        order = np.argsort(-w)
        return [int(i) for i in order[:k_eff]]


def _starter_like_scores(players: pd.DataFrame, minutes_weights: np.ndarray) -> np.ndarray:
    n = int(len(players))
    if n <= 0:
        return np.zeros(0, dtype=float)

    scores = np.zeros(n, dtype=float)
    try:
        if "starter_prob" in players.columns:
            starter_prob = _safe_series(players, "starter_prob").to_numpy(dtype=float)
            starter_prob = np.where(np.isfinite(starter_prob), np.clip(starter_prob, 0.0, 1.0), 0.0)
            scores = np.maximum(scores, starter_prob)
    except Exception:
        pass

    try:
        if "is_starter" in players.columns:
            ser = players["is_starter"]
            txt = ser.astype(str).str.strip().str.lower().isin({"1", "true", "t", "yes", "y"}).to_numpy(dtype=bool)
            num = pd.to_numeric(ser, errors="coerce").fillna(0.0).to_numpy(dtype=float) > 0.5
            scores = np.maximum(scores, (txt | num).astype(float))
    except Exception:
        pass

    try:
        if int(np.sum(scores >= 0.55)) < min(5, n):
            w = np.maximum(0.0, np.asarray(minutes_weights, dtype=float))
            order = np.argsort(-w)
            top_n = int(min(5, n))
            if top_n > 0:
                ramp = np.linspace(1.0, 0.72, top_n)
                scores[order[:top_n]] = np.maximum(scores[order[:top_n]], ramp)
    except Exception:
        pass

    return np.clip(scores, 0.0, 1.0)


def _scoring_like_scores(players: pd.DataFrame) -> np.ndarray:
    n = int(len(players))
    if n <= 0:
        return np.zeros(0, dtype=float)

    pred = np.maximum(0.0, _safe_series(players, "pred_pts").to_numpy(dtype=float))
    if float(np.sum(pred)) <= 0.0:
        fga = np.maximum(0.0, _safe_series(players, "_prior_fga_pm").to_numpy(dtype=float))
        threes = np.maximum(0.0, _safe_series(players, "_prior_threes_att_pm").to_numpy(dtype=float))
        pred = fga + (0.75 * threes)

    pred = np.log1p(np.maximum(0.0, np.where(np.isfinite(pred), pred, 0.0)))
    pos = pred[pred > 0.0]
    if pos.size <= 0:
        return np.zeros(n, dtype=float)

    try:
        hi = float(np.quantile(pos, 0.85))
    except Exception:
        hi = float(np.max(pos)) if pos.size else 0.0
    if (not np.isfinite(hi)) or hi <= 0.0:
        hi = float(np.max(pos)) if pos.size else 0.0
    if (not np.isfinite(hi)) or hi <= 0.0:
        return np.zeros(n, dtype=float)

    return np.clip(pred / hi, 0.0, 1.0)


def _rotation_windows(q: int, period_seconds: int, q_remaining: int, margin: int, *, lp: LeagueParams) -> Dict[str, bool]:
    # Quarters: half starts (1, 3), half ends (2, 4), last 4, first-half end 2 -- exactly the vendored literals.
    # The second-by-second thresholds are the vendored NBA values in every league (P3/P4 own any re-fit).
    qi = int(q)
    rem = max(0, int(q_remaining))
    elapsed = max(0, int(period_seconds) - rem)
    abs_margin = abs(int(margin))
    last = int(lp.regulation_periods)
    half_start = lp.half_start_periods
    half_end = lp.half_end_periods
    first_half_end = half_end[0]
    is_reg = 1 <= qi <= last
    return {
        "opening_stint": bool(is_reg and qi in half_start and elapsed < 180),
        "bench_stint": bool(is_reg and qi in half_end and elapsed < 180),
        "mid_wave": bool(is_reg and qi in half_start and 180 <= elapsed < 420),
        "closing_window": bool(is_reg and qi in half_end and rem <= 210 and abs_margin <= 10),
        "crunch_time": bool(is_reg and qi == last and rem <= 180 and abs_margin <= 8),
        "late_half_push": bool(is_reg and qi == first_half_end and qi != last and rem <= 90 and abs_margin <= 12),
        "late_game_push": bool(is_reg and qi == last and rem <= 180 and abs_margin <= 14),
    }


def _contextual_minutes_weights(
    base_weights: np.ndarray,
    starter_scores: np.ndarray,
    scorer_scores: np.ndarray,
    *,
    flags: Dict[str, bool],
    team_is_trailing: bool,
    team_is_leading: bool,
    blowout: bool,
) -> np.ndarray:
    w = np.maximum(0.0, np.asarray(base_weights, dtype=float))
    if w.size <= 0:
        return w
    if float(np.sum(w)) <= 0.0:
        w = np.ones_like(w, dtype=float)

    starter = np.clip(np.asarray(starter_scores, dtype=float), 0.0, 1.0)
    scorer = np.clip(np.asarray(scorer_scores, dtype=float), 0.0, 1.0)
    if starter.size != w.size:
        starter = np.zeros_like(w, dtype=float)
    if scorer.size != w.size:
        scorer = np.zeros_like(w, dtype=float)

    closer = np.clip(np.maximum(starter, 0.75 * scorer), 0.0, 1.0)
    bench = 1.0 - starter
    factor = np.ones_like(w, dtype=float)

    if blowout:
        factor *= np.clip(0.76 + (0.58 * bench), 0.70, 1.35)
    else:
        if flags.get("opening_stint"):
            factor *= np.clip(0.88 + (0.28 * starter) + (0.06 * closer), 0.80, 1.30)
        if flags.get("bench_stint"):
            factor *= np.clip(0.92 + (0.24 * bench), 0.82, 1.28)
        if flags.get("mid_wave"):
            factor *= np.clip(0.95 + (0.18 * bench), 0.88, 1.22)
        if flags.get("closing_window"):
            factor *= np.clip(0.82 + (0.28 * closer), 0.78, 1.30)
        if flags.get("crunch_time"):
            factor *= np.clip(0.88 + (0.18 * closer), 0.84, 1.25)
        if bool(team_is_trailing) and (flags.get("late_half_push") or flags.get("late_game_push")):
            factor *= np.clip(0.92 + (0.16 * np.maximum(starter, scorer)), 0.88, 1.25)
        elif bool(team_is_leading) and flags.get("late_game_push"):
            factor *= np.clip(0.94 + (0.12 * starter) + (0.04 * bench), 0.90, 1.18)

    w = np.where(np.isfinite(w * factor), w * factor, 0.0)
    if float(np.sum(w)) <= 0.0:
        return np.ones_like(w, dtype=float)
    return np.maximum(1e-6, w)


def _contextual_duration_scale(
    *,
    flags: Dict[str, bool],
    team_is_trailing: bool,
    team_is_leading: bool,
    blowout: bool,
) -> float:
    scale = 1.0
    if blowout:
        scale *= 1.08
    else:
        if flags.get("opening_stint"):
            scale *= 0.97
        if flags.get("bench_stint"):
            scale *= 1.05
        if flags.get("mid_wave"):
            scale *= 1.02
        if flags.get("closing_window"):
            scale *= 0.96
        if bool(team_is_trailing) and (flags.get("late_half_push") or flags.get("late_game_push")):
            scale *= 0.93
        elif bool(team_is_leading) and flags.get("late_game_push"):
            scale *= 1.04
    return float(np.clip(scale, 0.88, 1.12))


def _team_rates_from_priors(players: pd.DataFrame, cfg: EventSimConfig, *, lp: LeagueParams) -> Dict[str, float]:
    """Derive team-level per-possession / per-FGA rates from player per-minute priors."""
    mins = _safe_series(players, "_sim_min").to_numpy(dtype=float)
    total_min = float(np.sum(np.maximum(0.0, mins)))
    if total_min <= 0:
        total_min = float(lp.regulation_team_minutes)

    def per_game_from_pm(col_pm: str) -> float:
        pm = _safe_series(players, col_pm).to_numpy(dtype=float)
        return float(np.sum(np.maximum(0.0, pm) * np.maximum(0.0, mins)))

    fga = per_game_from_pm("_prior_fga_pm")
    fg3a = per_game_from_pm("_prior_threes_att_pm")
    fta = per_game_from_pm("_prior_fta_pm")
    tov = per_game_from_pm("_prior_tov_pm")
    pf = per_game_from_pm("_prior_pf_pm")

    poss = max(float(lp.min_rate_possessions), float(cfg.possessions_per_game))

    p_tov = float(np.clip(tov / poss, 0.05, 0.22)) if np.isfinite(tov) and tov > 0 else cfg.base_tov_per_poss
    p3 = float(np.clip(fg3a / max(1.0, fga), 0.18, 0.55)) if np.isfinite(fga) and fga > 0 else 0.36
    foul_per_fga = float(np.clip(fta / max(1.0, fga), 0.05, 0.20)) if np.isfinite(fga) and fga > 0 else cfg.base_shooting_foul_per_fga

    # PF per possession (includes non-shooting; rough)
    pf_per_poss = float(np.clip(pf / poss, 0.10, 0.30)) if np.isfinite(pf) and pf > 0 else 0.18

    return {
        "poss": poss,
        "p_tov": p_tov,
        "p3": p3,
        "foul_per_fga": foul_per_fga,
        "pf_per_poss": pf_per_poss,
    }


def _player_pct(players: pd.DataFrame, made_pm: str, att_pm: str, default: float, lo: float, hi: float) -> np.ndarray:
    made = _safe_series(players, made_pm).to_numpy(dtype=float)
    att = _safe_series(players, att_pm).to_numpy(dtype=float)
    with np.errstate(divide="ignore", invalid="ignore"):
        pct = np.where(att > 0, made / att, np.nan)
    pct = np.where(np.isfinite(pct), pct, default)
    return np.clip(pct, lo, hi)


# The vendored module switches (SHOOTER_FT_RATE, FOULED_MISS_NOT_FGA, EXACT_TARGET_CALIBRATION, TOV_PER_ATTEMPT,
# PLAYER_REBOUND_CREDIT and its credits, BLOCK_MODE, LEAGUE_BLOCKS_PER_MISSED_2PA, BLOCK_RATE_ASSUMED_FG3_PCT,
# BLOCK_ALLOC_BY_RATE / _FLOOR_PM) are LeagueParams fields now; see league.py for each one's provenance.


def _ft_rate_multipliers(players: pd.DataFrame, minutes: np.ndarray) -> np.ndarray:
    """Per-player (FTA/FGA) / team shot-weighted mean, clipped to [0.3, 3]; 1.0 when unknown."""
    fta = _safe_series(players, "_prior_fta_pm").to_numpy(dtype=float)
    fga = _safe_series(players, "_prior_fga_pm").to_numpy(dtype=float)
    mins = np.where(np.isfinite(minutes), np.maximum(minutes, 0.0), 0.0)
    ok = np.isfinite(fta) & np.isfinite(fga) & (fga > 0) & (fta >= 0)
    ratio = np.where(ok, fta / np.where(fga > 0, fga, 1.0), np.nan)
    shots = np.where(ok, fga * mins, 0.0)
    if float(shots.sum()) <= 0:
        return np.ones(len(fta), dtype=float)
    team = float(np.nansum(ratio * shots) / shots.sum())
    if not np.isfinite(team) or team <= 0:
        return np.ones(len(fta), dtype=float)
    mult = np.where(ok, np.clip(ratio / team, 0.3, 3.0), 1.0)
    # Re-normalise after clipping so the shot-weighted mean multiplier stays 1.
    w = np.where(ok, fga * mins, 0.0)
    if float(w.sum()) > 0:
        mean = float((mult * w).sum() / w.sum())
        if mean > 0:
            mult = np.where(ok, mult / mean, 1.0)
    return mult


def _iterations_per_possession(p_tov: float, p3: float, fg2: float, fg3: float, foul: float, oreb: float) -> float:
    """1 + c: the loop's expected shot iterations per possession (see _loop_points_per_possession)."""
    t = float(np.clip(p_tov, 0.0, 0.6))
    s3 = float(np.clip(p3, 0.0, 1.0))
    made = (1.0 - s3) * float(np.clip(fg2, 0.05, 0.95)) + s3 * float(np.clip(fg3, 0.05, 0.95))
    f = float(np.clip(foul, 0.0, 0.95))
    o = float(np.clip(oreb, 0.05, 0.55))
    return 1.0 + (1.0 - t) * (1.0 - made) * (1.0 - 0.70 * f) * o


def _loop_points_per_possession(p_tov: float, p3: float, fg2: float, fg3: float, foul: float, ft: float, oreb: float, eff: float) -> float:
    """Expected points per team possession under the PBP loop's own rules at multiplier `eff`.

    The 0.32 (and-one) and 0.70 (fouled miss -> free throws) shares are the loop's own constants below.
    """
    t = float(np.clip(p_tov, 0.0, 0.6))
    s3 = float(np.clip(p3, 0.0, 1.0))
    m2 = float(np.clip(fg2 * eff, 0.05, 0.95))
    m3 = float(np.clip(fg3 * eff, 0.05, 0.95))
    ftp = float(np.clip(ft * eff, 0.45, 0.95))
    f = float(np.clip(foul, 0.0, 0.95))
    o = float(np.clip(oreb, 0.05, 0.55))
    made = (1.0 - s3) * m2 + s3 * m3
    pts = (1.0 - s3) * m2 * 2.0 + s3 * m3 * 3.0
    pts += made * f * 0.32 * ftp
    pts += f * 0.70 * ftp * ((1.0 - s3) * (1.0 - m2) * 2.0 + s3 * (1.0 - m3) * 3.0)
    cont = (1.0 - t) * (1.0 - made) * (1.0 - 0.70 * f) * o
    # Iterations per possession are 1 + cont, not 1 / (1 - cont): every attempt spends period/q_poss seconds, so the
    # quarter clock reaches 0 before the possessions run out and the loop then refuses every later
    # offensive-rebound continuation (`q_remaining > 0`). Measured on the WNBA loop 2026-10-01 (1.1016 per possession
    # vs 1 + c = 1.1041); the NBA loop has the same clock rule (12-minute quarters, same avg_sec = period / q_poss).
    return float((1.0 - t) * pts * (1.0 + cont))


def _loop_shot_share(players: pd.DataFrame, minutes: np.ndarray, col_pm: str) -> np.ndarray:
    """Each player's expected share of the loop's shots for `col_pm`, as `_player_usage_weights` deals them.

    Within a lineup a shot goes 0.8 x (0.75 x log1p(rate) share + 0.25 x minutes share)
    + 0.2 x log1p(pred_pts) share; over a game a player is on court in proportion to minutes.
    """
    mins = np.maximum(0.0, np.where(np.isfinite(minutes), minutes, 0.0))
    if float(mins.sum()) <= 0:
        return np.full(len(mins), 1.0 / max(1, len(mins)))
    a = np.log1p(np.maximum(0.0, _safe_series(players, col_pm).to_numpy(dtype=float)))
    b = np.log1p(np.maximum(0.0, _safe_series(players, "pred_pts").to_numpy(dtype=float)))
    a_bar = float((a * mins).sum() / mins.sum())
    b_bar = float((b * mins).sum() / mins.sum())
    a_rel = a / a_bar if a_bar > 0 else np.ones(len(a))
    if b_bar > 0:
        rel = 0.6 * a_rel + 0.2 + 0.2 * (b / b_bar)
    else:  # no pred_pts: the loop drops that term
        rel = 0.75 * a_rel + 0.25
    share = mins * rel
    return share / share.sum()


def _solve_eff_mult(target_ppp: float, p_tov: float, p3: float, fg2: float, fg3: float, foul: float, ft: float, oreb: float, lo: float = 0.70, hi: float = 1.30) -> float:
    """Bisection for eff with _loop_points_per_possession(eff) == target_ppp, clipped to [lo, hi]."""
    if not np.isfinite(target_ppp) or target_ppp <= 0:
        return 1.0
    args = (p_tov, p3, fg2, fg3, foul, ft, oreb)
    if _loop_points_per_possession(*args, lo) >= target_ppp:
        return float(lo)
    if _loop_points_per_possession(*args, hi) <= target_ppp:
        return float(hi)
    a, b = lo, hi
    for _ in range(40):
        mid = 0.5 * (a + b)
        if _loop_points_per_possession(*args, mid) < target_ppp:
            a = mid
        else:
            b = mid
    return float(0.5 * (a + b))


def _team_block_rate_on_missed_2pa(def_players: pd.DataFrame, def_mins: np.ndarray, off_players: pd.DataFrame, off_mins: np.ndarray, off_rates: Dict[str, float], off_fg_pct: np.ndarray, off_eff: float, possessions: float, oreb: float, ft_mult: Optional[np.ndarray] = None, *, lp: LeagueParams) -> float:
    """Defense's prior blocks per game / the missed 2PAs the LOOP will produce for the offense.

    The denominator is the loop's own expectation (possessions x shot iterations x 2PA share x miss rate at the
    solved efficiency), not the priors' FGA: OREB continuation and the target solver change how many twos are
    missed, and a prior-FGA denominator over-blocked by ~20% (WNBA).
    """
    try:
        dm = np.maximum(0.0, np.where(np.isfinite(def_mins), def_mins, 0.0))
        om = np.maximum(0.0, np.where(np.isfinite(off_mins), off_mins, 0.0))
        blk = float(np.sum(np.maximum(0.0, _safe_series(def_players, "_prior_blk_pm").to_numpy(dtype=float)) * dm))
        share = _loop_shot_share(off_players, om, "_prior_fga_pm")
        fg2 = float(np.clip(float(np.sum(np.asarray(off_fg_pct, dtype=float) * share)) * float(off_eff), 0.05, 0.95))
        t = float(off_rates["p_tov"])
        p3 = float(np.clip(off_rates["p3"], 0.0, 0.9))
        foul = float(off_rates["foul_per_fga"]) * (float(np.sum(share * np.asarray(ft_mult, dtype=float))) if ft_mult is not None else 1.0)
        iters = _iterations_per_possession(p_tov=t, p3=p3, fg2=fg2, fg3=float(lp.block_rate_assumed_fg3_pct) * float(off_eff), foul=foul, oreb=oreb)
        missed2 = float(possessions) * iters * (1.0 - t) * (1.0 - p3) * (1.0 - fg2)
        if blk <= 0.0 or missed2 <= 1.0:
            return lp.league_blocks_per_missed_2pa
        return float(np.clip(blk / missed2, 0.05, 0.40))
    except Exception:
        return lp.league_blocks_per_missed_2pa


def _block_drawn(rng: np.random.Generator, shot_is_3: bool, made: bool, legacy_rate: float, rate_on_missed_2pa: float, *, lp: LeagueParams) -> bool:
    if lp.block_mode == "legacy":
        # Exactly the old expression: no draw on a three (short-circuit), one draw on every 2PA.
        return bool((not shot_is_3) and (rng.random() < legacy_rate))
    if shot_is_3 or made:
        return False
    return bool(rng.random() < float(np.clip(rate_on_missed_2pa, 0.0, 0.9)))


def _player_rebound_credited(rng: np.random.Generator, offensive: bool, *, lp: LeagueParams) -> bool:
    if not lp.player_rebound_credit:
        return True  # no draw: the old credit-every-miss path
    p = lp.oreb_player_credit if offensive else lp.dreb_player_credit
    return bool(rng.random() < min(1.0, max(0.0, p)))


def _player_usage_weights(players: pd.DataFrame, col_pm: str, lineup_idx: List[int], *, lp: LeagueParams) -> np.ndarray:
    """Return selection weights for the current on-court lineup.

    Key realism guardrail:
    - We *blend* priors with minutes so missing/zero priors don't collapse usage onto a single player.
      This was a major cause of "inflated" statlines (one player with nonzero priors getting nearly
      all shots/assists/rebounds simply because others had 0 priors).
    """
    n = int(len(players))
    if n <= 0:
        return np.zeros(0, dtype=float)

    pm = _safe_series(players, col_pm).to_numpy(dtype=float)
    pm = np.maximum(0.0, np.where(np.isfinite(pm), pm, 0.0))
    if lp.block_alloc_by_rate and col_pm == "_prior_blk_pm":
        w = np.zeros(n, dtype=float)
        idx = [int(i) for i in (lineup_idx or []) if 0 <= int(i) < n]
        if not idx:
            return w
        line = np.maximum(pm[idx], lp.block_alloc_floor_pm)
        line = line / float(line.sum())
        for j, i in enumerate(idx):
            w[int(i)] = float(line[j])
        return w
    # Compress outliers (robust even if a bad prior slips through).
    pm = np.log1p(pm)

    mins = _safe_series(players, "_sim_min").to_numpy(dtype=float)
    mins = np.maximum(0.0, np.where(np.isfinite(mins), mins, 0.0))

    w = np.zeros(n, dtype=float)
    idx = [int(i) for i in (lineup_idx or []) if 0 <= int(i) < n]
    if not idx:
        return w

    pm_line = pm[idx]
    mins_line = mins[idx]

    # Minutes provide a stable floor so everyone can accrue events.
    mins_floor = np.maximum(1.0, mins_line)
    s_m = float(mins_floor.sum())
    mins_norm = (mins_floor / s_m) if np.isfinite(s_m) and s_m > 0 else np.full(len(idx), 1.0 / len(idx))

    s_p = float(pm_line.sum())

    # Optional: anchor shot selection to predicted points so stars reliably get
    # appropriate volume even when per-minute priors are noisy.
    pred_weight = 0.0
    pred_norm = None
    if col_pm in ("_prior_fga_pm", "_prior_threes_att_pm"):
        try:
            pred = _safe_series(players, "pred_pts").to_numpy(dtype=float)
            pred = np.maximum(0.0, np.where(np.isfinite(pred), pred, 0.0))
            pred = np.log1p(pred)
            pred_line = pred[idx]
            s_pred = float(pred_line.sum())
            if np.isfinite(s_pred) and s_pred > 0:
                pred_norm = pred_line / s_pred
                pred_weight = 0.20
        except Exception:
            pred_weight = 0.0
            pred_norm = None

    if (not np.isfinite(s_p)) or s_p <= 0:
        probs = mins_norm
        if pred_norm is not None and pred_weight > 0:
            # If priors are missing, still allow pred_pts to shape volume a bit.
            probs = pred_weight * pred_norm + (1.0 - pred_weight) * mins_norm
    else:
        pm_norm = pm_line / s_p
        # Priors-heavy but never priors-only.
        pri_weight = 0.75
        base = pri_weight * pm_norm + (1.0 - pri_weight) * mins_norm
        if pred_norm is not None and pred_weight > 0:
            probs = (1.0 - pred_weight) * base + pred_weight * pred_norm
        else:
            probs = base

    probs = np.maximum(0.0, probs)
    s = float(probs.sum())
    if not np.isfinite(s) or s <= 0:
        probs = np.full(len(idx), 1.0 / len(idx))
    else:
        probs = probs / s

    # Convert back into weights on the full player index space.
    for j, i in enumerate(idx):
        w[int(i)] = float(probs[j])
    return w


def simulate_event_level_boxscore(
    rng: np.random.Generator,
    home_players: pd.DataFrame,
    away_players: pd.DataFrame,
    home_q_pts: List[int],
    away_q_pts: List[int],
    cfg: Optional[EventSimConfig] = None,
    home_lineups: Optional[List[List[int]]] = None,
    home_lineup_weights: Optional[np.ndarray] = None,
    away_lineups: Optional[List[List[int]]] = None,
    away_lineup_weights: Optional[np.ndarray] = None,
    home_team_adj: Optional[Dict[str, float]] = None,
    away_team_adj: Optional[Dict[str, float]] = None,
    *,
    league: LeagueParams,
    sample_lineup: Optional[Callable[..., List[int]]] = None,
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """REFUSES. The legacy non-PBP simulator was never ported, because it never worked.

    In BOTH vendored copies it raised ``NameError: name 'period_seconds' is not
    defined`` on its first possession (vendored events.py:796 passes
    ``period_seconds=int(period_seconds)`` from a scope that has no
    ``period_seconds``), so every call failed, for every input. Measured
    2026-10-09, lane basketball-native-engine: 9 of 9 synthetic cases raised in
    the vendored engine. Production does not reach it: the smart sim runs
    ``use_pbp=True`` (REFRESH_PREDICT_PROPS_SMART_SIM_PBP defaults on). A
    caller that asks for it still fails, as before, but with a named refusal
    instead of a NameError.
    """
    raise NotImplementedError(
        "simulate_event_level_boxscore: the legacy non-PBP basketball simulator was broken in the vendored engine "
        "(NameError on its first possession) and is not ported; use simulate_pbp_game_boxscore (use_pbp=True)"
    )


def _expected_points_per_possession(
    p_tov: float,
    p3: float,
    fg2_pct: float,
    fg3_pct: float,
    foul_per_fga: float,
    ft_pct: float,
    oreb_rate: float = 0.24,
) -> float:
    """Very rough expected points per possession from rate inputs.

    Used only to compute a small efficiency multiplier to match a target PPP.
    """
    try:
        p_tov = float(np.clip(p_tov, 0.01, 0.35))
        p3 = float(np.clip(p3, 0.05, 0.75))
        fg2_pct = float(np.clip(fg2_pct, 0.20, 0.80))
        fg3_pct = float(np.clip(fg3_pct, 0.15, 0.60))
        foul_per_fga = float(np.clip(foul_per_fga, 0.02, 0.30))
        ft_pct = float(np.clip(ft_pct, 0.45, 0.95))
    except Exception:
        return 1.05

    # Assume each non-TOV possession produces ~1 FGA.
    # A fraction of FGAs become shooting fouls; those yield FTs instead of a shot result.
    p_shot_poss = 1.0 - p_tov
    p_shooting_foul = float(np.clip(foul_per_fga * 0.70, 0.0, 0.35))
    p_live_shot = max(0.0, 1.0 - p_shooting_foul)

    exp_from_fg = p_live_shot * ((1.0 - p3) * (2.0 * fg2_pct) + p3 * (3.0 * fg3_pct))
    # FTs: mix 2/3 shots by p3
    exp_fts = p_shooting_foul * (((1.0 - p3) * 2.0) + (p3 * 3.0)) * ft_pct

    base = p_shot_poss * (exp_from_fg + exp_fts)

    # Offensive rebounds extend the same possession and create additional shot chances.
    # Approximate with a geometric continuation factor.
    try:
        oreb_rate = float(np.clip(float(oreb_rate), 0.05, 0.45))
        p_make_live = float(np.clip((1.0 - p3) * fg2_pct + p3 * fg3_pct, 0.05, 0.95))
        p_miss_live = 1.0 - p_make_live
        # Only live-shot misses can lead to OREBs.
        p_cont = float(np.clip(p_shot_poss * p_live_shot * p_miss_live * oreb_rate, 0.0, 0.35))
        mult = 1.0 / max(1e-6, (1.0 - p_cont))
        return float(base * mult)
    except Exception:
        return float(base)


def simulate_pbp_game_boxscore(
    rng: np.random.Generator,
    home_players: pd.DataFrame,
    away_players: pd.DataFrame,
    cfg: Optional[EventSimConfig] = None,
    home_lineups: Optional[List[List[int]]] = None,
    home_lineup_weights: Optional[np.ndarray] = None,
    away_lineups: Optional[List[List[int]]] = None,
    away_lineup_weights: Optional[np.ndarray] = None,
    target_home_points: Optional[float] = None,
    target_away_points: Optional[float] = None,
    quarters: Optional[List[Any]] = None,
    home_team_adj: Optional[Dict[str, float]] = None,
    away_team_adj: Optional[Dict[str, float]] = None,
    *,
    league: LeagueParams,
    sample_lineup: Optional[Callable[..., List[int]]] = None,
    state: Optional[GameState] = None,
) -> Tuple[Dict[str, Any], Dict[str, Any], List[int], List[int]]:
    """Simulate a possession/play-by-play style game.

    This produces quarter points and player props from one shared possession stream,
    so correlations emerge naturally (pace/efficiency/usage/lineups affect everything).

    Returns (home_box, away_box, home_q_pts, away_q_pts).
    """
    lp = league
    cfg = cfg or EventSimConfig(possessions_per_game=float(lp.default_possessions_per_game))
    sample_lineup = sample_lineup or sample_lineup_minutes_weighted
    _usage_w = partial(_player_usage_weights, lp=lp)
    _rates = partial(_team_rates_from_priors, lp=lp)
    _windows = partial(_rotation_windows, lp=lp)
    _blk_drawn = partial(_block_drawn, lp=lp)
    _reb_credited = partial(_player_rebound_credited, lp=lp)
    SHOOTER_FT_RATE = bool(lp.shooter_ft_rate)
    FOULED_MISS_NOT_FGA = bool(lp.fouled_miss_not_fga)
    EXACT_TARGET_CALIBRATION = bool(lp.exact_target_calibration)
    TOV_PER_ATTEMPT = bool(lp.tov_per_attempt)
    BLOCK_MODE = str(lp.block_mode)
    LEAGUE_BLOCKS_PER_MISSED_2PA = float(lp.league_blocks_per_missed_2pa)
    N_PERIODS = int(lp.regulation_periods)
    HALF_END = lp.half_end_periods

    def _adj_value(adj: Optional[Dict[str, float]], key: str, default: float = 1.0, lo: float = 0.5, hi: float = 1.5) -> float:
        try:
            if not isinstance(adj, dict):
                return float(default)
            v = float(adj.get(key, default))
            if not np.isfinite(v):
                return float(default)
            return float(np.clip(v, lo, hi))
        except Exception:
            return float(default)

    # Precompute weights and rates
    h_mins = _safe_series(home_players, "_sim_min").to_numpy(dtype=float)
    a_mins = _safe_series(away_players, "_sim_min").to_numpy(dtype=float)
    h_rates = _rates(home_players, cfg)
    a_rates = _rates(away_players, cfg)

    # Optional team-level adjustments (e.g., from team advanced priors). Kept bounded.
    eff_prior_h = _adj_value(home_team_adj, "eff_mult", 1.0, lo=0.80, hi=1.20)
    eff_prior_a = _adj_value(away_team_adj, "eff_mult", 1.0, lo=0.80, hi=1.20)
    tov_mult_h = _adj_value(home_team_adj, "tov_mult", 1.0, lo=0.85, hi=1.15)
    tov_mult_a = _adj_value(away_team_adj, "tov_mult", 1.0, lo=0.85, hi=1.15)
    foul_mult_h = _adj_value(home_team_adj, "foul_mult", 1.0, lo=0.80, hi=1.25)
    foul_mult_a = _adj_value(away_team_adj, "foul_mult", 1.0, lo=0.80, hi=1.25)
    oreb_mult_h = _adj_value(home_team_adj, "oreb_mult", 1.0, lo=0.75, hi=1.35)
    oreb_mult_a = _adj_value(away_team_adj, "oreb_mult", 1.0, lo=0.75, hi=1.35)

    h_rates = dict(h_rates)
    a_rates = dict(a_rates)
    try:
        h_rates["p_tov"] = float(np.clip(float(h_rates.get("p_tov", cfg.base_tov_per_poss)) * tov_mult_h, 0.04, 0.28))
        a_rates["p_tov"] = float(np.clip(float(a_rates.get("p_tov", cfg.base_tov_per_poss)) * tov_mult_a, 0.04, 0.28))
    except Exception:
        pass
    try:
        h_rates["foul_per_fga"] = float(np.clip(float(h_rates.get("foul_per_fga", cfg.base_shooting_foul_per_fga)) * foul_mult_h, 0.03, 0.35))
        a_rates["foul_per_fga"] = float(np.clip(float(a_rates.get("foul_per_fga", cfg.base_shooting_foul_per_fga)) * foul_mult_a, 0.03, 0.35))
    except Exception:
        pass

    # Player shooting pcts
    h_fg_pct = _player_pct(home_players, "_prior_fgm_pm", "_prior_fga_pm", default=0.46, lo=0.25, hi=0.75)
    a_fg_pct = _player_pct(away_players, "_prior_fgm_pm", "_prior_fga_pm", default=0.46, lo=0.25, hi=0.75)
    h_3p_pct = _player_pct(home_players, "_prior_threes_pm", "_prior_threes_att_pm", default=0.35, lo=0.20, hi=0.50)
    a_3p_pct = _player_pct(away_players, "_prior_threes_pm", "_prior_threes_att_pm", default=0.35, lo=0.20, hi=0.50)
    h_ft_pct = _player_pct(home_players, "_prior_ftm_pm", "_prior_fta_pm", default=0.76, lo=0.45, hi=0.95)
    a_ft_pct = _player_pct(away_players, "_prior_ftm_pm", "_prior_fta_pm", default=0.76, lo=0.45, hi=0.95)
    # Per-shooter FT-rate multipliers (SHOOTER_FT_RATE). Deterministic, no draws; neutral 1.0 if anything fails.
    if lp.ft_mult_errors_neutral:
        try:
            h_ft_mult = _ft_rate_multipliers(home_players, h_mins)
            a_ft_mult = _ft_rate_multipliers(away_players, a_mins)
        except Exception:
            h_ft_mult = np.ones(len(home_players), dtype=float)
            a_ft_mult = np.ones(len(away_players), dtype=float)
    else:
        h_ft_mult = _ft_rate_multipliers(home_players, h_mins)
        a_ft_mult = _ft_rate_multipliers(away_players, a_mins)
    h_starter_scores = _starter_like_scores(home_players, h_mins)
    a_starter_scores = _starter_like_scores(away_players, a_mins)
    h_scorer_scores = _scoring_like_scores(home_players)
    a_scorer_scores = _scoring_like_scores(away_players)

    if TOV_PER_ATTEMPT:
        try:
            for rates, players, mins, fg_v, fg3_v, ftm_v, oreb_m in (
                (h_rates, home_players, h_mins, h_fg_pct, h_3p_pct, h_ft_mult, oreb_mult_h),
                (a_rates, away_players, a_mins, a_fg_pct, a_3p_pct, a_ft_mult, oreb_mult_a),
            ):
                share = _loop_shot_share(players, mins, "_prior_fga_pm")
                share3 = _loop_shot_share(players, mins, "_prior_threes_att_pm")
                foul_share = share * (np.asarray(ftm_v, dtype=float) if SHOOTER_FT_RATE else 1.0)
                iters = _iterations_per_possession(
                    p_tov=float(rates["p_tov"]),
                    p3=float(rates["p3"]),
                    fg2=float(np.sum(np.asarray(fg_v, dtype=float) * share)),
                    fg3=float(np.sum(np.asarray(fg3_v, dtype=float) * share3)),
                    foul=float(rates["foul_per_fga"]) * float(np.sum(foul_share)),
                    oreb=float(cfg.base_oreb_rate) * float(oreb_m),
                )
                rates["p_tov"] = float(rates["p_tov"]) / max(1.0, iters)
        except Exception:
            pass

    def _team_avg(arr: np.ndarray, w: np.ndarray, default: float) -> float:
        try:
            ww = np.maximum(0.0, np.asarray(w, dtype=float))
            aa = np.asarray(arr, dtype=float)
            if ww.size != aa.size or ww.size == 0:
                return float(default)
            s = float(np.sum(ww))
            if not np.isfinite(s) or s <= 0:
                return float(np.nanmean(aa)) if np.isfinite(np.nanmean(aa)) else float(default)
            return float(np.sum(aa * ww) / s)
        except Exception:
            return float(default)

    # Small efficiency calibration toward target points (keeps market/model alignment)
    poss = float(np.mean([h_rates.get("poss", cfg.possessions_per_game), a_rates.get("poss", cfg.possessions_per_game)]))
    poss = float(max(70.0, poss))
    tpp_h = float(target_home_points) / poss if target_home_points is not None and np.isfinite(float(target_home_points)) else None
    tpp_a = float(target_away_points) / poss if target_away_points is not None and np.isfinite(float(target_away_points)) else None

    base_ppp_h = _expected_points_per_possession(
        p_tov=float(h_rates["p_tov"]),
        p3=float(h_rates["p3"]),
        fg2_pct=_team_avg(h_fg_pct, h_mins, 0.46),
        fg3_pct=_team_avg(h_3p_pct, h_mins, 0.35),
        foul_per_fga=float(h_rates["foul_per_fga"]),
        ft_pct=_team_avg(h_ft_pct, h_mins, 0.76),
        oreb_rate=float(cfg.base_oreb_rate) * float(oreb_mult_h),
    )
    base_ppp_a = _expected_points_per_possession(
        p_tov=float(a_rates["p_tov"]),
        p3=float(a_rates["p3"]),
        fg2_pct=_team_avg(a_fg_pct, a_mins, 0.46),
        fg3_pct=_team_avg(a_3p_pct, a_mins, 0.35),
        foul_per_fga=float(a_rates["foul_per_fga"]),
        ft_pct=_team_avg(a_ft_pct, a_mins, 0.76),
        oreb_rate=float(cfg.base_oreb_rate) * float(oreb_mult_a),
    )

    eff_mult_h = 1.0
    eff_mult_a = 1.0
    try:
        if tpp_h is not None and base_ppp_h > 1e-6:
            eff_mult_h = float(np.clip(tpp_h / base_ppp_h, 0.85, 1.15))
        if tpp_a is not None and base_ppp_a > 1e-6:
            eff_mult_a = float(np.clip(tpp_a / base_ppp_a, 0.85, 1.15))
    except Exception:
        eff_mult_h = 1.0
        eff_mult_a = 1.0
    if EXACT_TARGET_CALIBRATION:
        try:
            def _vol_avg(pct: np.ndarray, players: pd.DataFrame, mins: np.ndarray, att_cols: Tuple[str, ...], default: float) -> float:
                # Weighted the way the loop hands out the attempts, not by raw volume.
                return _team_avg(pct, _loop_shot_share(players, mins, att_cols[0]), default)

            for side, tpp in (("h", tpp_h), ("a", tpp_a)):
                if tpp is None:
                    continue
                players, mins, rates = (home_players, h_mins, h_rates) if side == "h" else (away_players, a_mins, a_rates)
                fg2v = h_fg_pct if side == "h" else a_fg_pct
                fg3v = h_3p_pct if side == "h" else a_3p_pct
                ftv = h_ft_pct if side == "h" else a_ft_pct
                oreb_m = oreb_mult_h if side == "h" else oreb_mult_a
                # Fouls (and so FTs) land on shooters by the loop's shot share x each shooter's FT-rate multiplier,
                # so the effective team foul rate and the FT% that applies are averaged that way too.
                shot_share = _loop_shot_share(players, mins, "_prior_fga_pm")
                ft_mult = (h_ft_mult if side == "h" else a_ft_mult) if SHOOTER_FT_RATE else np.ones(len(shot_share))
                foul_share = shot_share * np.asarray(ft_mult, dtype=float)
                solved = _solve_eff_mult(
                    float(tpp),
                    p_tov=float(rates["p_tov"]),
                    p3=float(rates["p3"]),
                    # 2PA shooters are picked by TOTAL FGA usage in the loop.
                    fg2=_team_avg(fg2v, shot_share, 0.50),
                    fg3=_vol_avg(fg3v, players, mins, ("_prior_threes_att_pm",), 0.34),
                    foul=float(rates["foul_per_fga"]) * float(foul_share.sum()),
                    ft=_team_avg(ftv, foul_share, 0.78),
                    oreb=float(cfg.base_oreb_rate) * float(oreb_m),
                )
                if side == "h":
                    eff_mult_h = solved
                else:
                    eff_mult_a = solved
        except Exception:
            pass

    # Apply opponent-aware/team prior efficiency multipliers (kept bounded).
    try:
        _stack = bool(getattr(cfg, "team_prior_stacks_on_target", True)) if lp.team_prior_stacks_on_target is None else bool(lp.team_prior_stacks_on_target)
        if _stack or tpp_h is None:
            eff_mult_h = float(np.clip(float(eff_mult_h) * float(eff_prior_h), 0.75, 1.25))
        if _stack or tpp_a is None:
            eff_mult_a = float(np.clip(float(eff_mult_a) * float(eff_prior_a), 0.75, 1.25))
    except Exception:
        pass

    # Home DEFENSE blocks away shots, and vice versa (at the final efficiencies). Only used outside "legacy".
    h_blk_rate = a_blk_rate = LEAGUE_BLOCKS_PER_MISSED_2PA
    if BLOCK_MODE != "legacy":
        h_blk_rate = _team_block_rate_on_missed_2pa(home_players, h_mins, away_players, a_mins, a_rates, a_fg_pct, eff_mult_a, poss,
                                                    float(np.clip(float(cfg.base_oreb_rate) * float(oreb_mult_a), 0.05, 0.55)), a_ft_mult if SHOOTER_FT_RATE else None, lp=lp)
        a_blk_rate = _team_block_rate_on_missed_2pa(away_players, a_mins, home_players, h_mins, h_rates, h_fg_pct, eff_mult_h, poss,
                                                    float(np.clip(float(cfg.base_oreb_rate) * float(oreb_mult_h), 0.05, 0.55)), h_ft_mult if SHOOTER_FT_RATE else None, lp=lp)

    # Aggregation arrays
    def blank(players: pd.DataFrame) -> Dict[str, np.ndarray]:
        n = int(len(players))
        return {
            "pts": np.zeros(n, dtype=int),
            "fga": np.zeros(n, dtype=int),
            "fgm": np.zeros(n, dtype=int),
            "fg3a": np.zeros(n, dtype=int),
            "fg3m": np.zeros(n, dtype=int),
            "fta": np.zeros(n, dtype=int),
            "ftm": np.zeros(n, dtype=int),
            "reb": np.zeros(n, dtype=int),
            "ast": np.zeros(n, dtype=int),
            "stl": np.zeros(n, dtype=int),
            "blk": np.zeros(n, dtype=int),
            "tov": np.zeros(n, dtype=int),
            "pf": np.zeros(n, dtype=int),
        }

    def blank_q(players: pd.DataFrame) -> Dict[str, np.ndarray]:
        n = int(len(players))
        # Only track the stats we expose as quarter-level props (keeps output size sane).
        return {
            "pts": np.zeros((N_PERIODS, n), dtype=int),
            "reb": np.zeros((N_PERIODS, n), dtype=int),
            "ast": np.zeros((N_PERIODS, n), dtype=int),
            "threes": np.zeros((N_PERIODS, n), dtype=int),
        }

    h = blank(home_players)
    a = blank(away_players)
    hq = blank_q(home_players)
    aq = blank_q(away_players)
    record_events = bool(getattr(cfg, "record_events", False))
    events: List[Dict[str, Any]] = []

    # RESUME set-up. GameState() is the opening tip: score 0-0, period 1, nothing forced, no draws spent here.
    state = state if state is not None else GameState()
    state.validate(lp)
    opening_tip = state.is_opening_tip(lp)
    start_period = 1 if opening_tip else int(state.period)
    resume_kwargs: Dict[str, Any] = {}
    h_out_idx: List[int] = []
    a_out_idx: List[int] = []
    if not opening_tip:
        full_left = state.period_seconds(lp)
        left = None if state.seconds_remaining is None or int(state.seconds_remaining) == int(full_left) else int(state.seconds_remaining)
        h_names = _player_names(home_players)
        a_names = _player_names(away_players)
        h_out = _fouled_out_names(state.home_player_fouls, lp)
        a_out = _fouled_out_names(state.away_player_fouls, lp)
        h_out_idx = [i for i, nm in enumerate(h_names) if nm in h_out]
        a_out_idx = [i for i, nm in enumerate(a_names) if nm in a_out]
        if h_out_idx:
            home_lineups, home_lineup_weights = _drop_lineups_with(home_lineups, home_lineup_weights, set(h_out_idx))
        if a_out_idx:
            away_lineups, away_lineup_weights = _drop_lineups_with(away_lineups, away_lineup_weights, set(a_out_idx))
        resume_kwargs = {
            "start_remaining": left,
            "first_offense_home": None if state.possession is None else bool(state.possession == "home"),
            "first_h_line": _lineup_indices(h_names, state.home_on_floor, side="home"),
            "first_a_line": _lineup_indices(a_names, state.away_on_floor, side="away"),
        }

    home_score = int(state.home_score)
    away_score = int(state.away_score)
    home_q_pts: List[int] = []
    away_q_pts: List[int] = []

    # Segment buckets for live-lens interval ladders.
    # Keep the legacy 3-minute buckets (4 per quarter) and ALSO track 1-minute buckets (12 per quarter).
    quarter_seconds = int(lp.regulation_period_seconds)
    segment_seconds = 3 * 60
    n_segments = int(max(1, np.ceil(float(quarter_seconds) / float(segment_seconds))))
    minute_seconds = 60
    n_minutes = int(max(1, quarter_seconds // minute_seconds))
    home_q_seg_pts = np.zeros((N_PERIODS, n_segments), dtype=int)
    away_q_seg_pts = np.zeros((N_PERIODS, n_segments), dtype=int)
    home_q_min_pts = np.zeros((N_PERIODS, n_minutes), dtype=int)
    away_q_min_pts = np.zeros((N_PERIODS, n_minutes), dtype=int)

    # Overtime settings (5 minutes in every league today)
    ot_seconds = int(lp.overtime_period_seconds)
    max_overtimes = 6
    home_ot_pts: List[int] = []
    away_ot_pts: List[int] = []

    def _add_q_stat(qarr: np.ndarray, q: int, idx: int, val: int) -> None:
        """Add to quarter-level arrays (only for regulation Q1-Q4)."""
        try:
            if 1 <= int(q) <= N_PERIODS:
                qarr[int(q) - 1, int(idx)] += int(val)
        except Exception:
            pass

    def _add_q_seg(segarr: np.ndarray, q: int, seg: int, val: int) -> None:
        """Add to 3-minute segment buckets (only for regulation Q1-Q4)."""
        try:
            if 1 <= int(q) <= N_PERIODS:
                segarr[int(q) - 1, int(seg)] += int(val)
        except Exception:
            pass

    def _add_q_min(minarr: np.ndarray, q: int, minute_idx: int, val: int) -> None:
        """Add to 1-minute segment buckets (only for regulation Q1-Q4)."""
        try:
            if 1 <= int(q) <= N_PERIODS:
                minarr[int(q) - 1, int(minute_idx)] += int(val)
        except Exception:
            pass

    def _pick_lineup_from_pool(
        pool: Optional[List[List[int]]],
        weights: Optional[np.ndarray],
        n_players: int,
    ) -> Optional[List[int]]:
        if not pool:
            return None
        valid: List[List[int]] = []
        w: List[float] = []
        for i, lu in enumerate(pool):
            try:
                idx = [int(x) for x in (lu or [])]
            except Exception:
                continue
            idx = [x for x in idx if 0 <= int(x) < int(n_players)]
            idx_u = list(dict.fromkeys(idx))
            if len(idx_u) != 5:
                continue
            valid.append(idx_u)
            if weights is not None and i < int(np.asarray(weights).size):
                try:
                    w.append(float(np.asarray(weights, dtype=float)[i]))
                except Exception:
                    w.append(1.0)
            else:
                w.append(1.0)
        if not valid:
            return None
        ww = np.asarray(w, dtype=float)
        ww = np.maximum(0.0, ww)
        s = float(np.sum(ww))
        probs = (ww / s) if (np.isfinite(s) and s > 0) else np.full(len(valid), 1.0 / len(valid))
        try:
            j = int(rng.choice(len(valid), p=probs))
            return valid[j]
        except Exception:
            return valid[int(rng.integers(0, len(valid)))]

    # Quarter loop
    # Precompute game-level target total from quarter model (if provided)
    game_mu_total = None
    try:
        if quarters and len(quarters) >= N_PERIODS:
            gm = float(sum(float(getattr(qr, "home_pts_mu", (qr or {}).get("home_pts_mu"))) + float(getattr(qr, "away_pts_mu", (qr or {}).get("away_pts_mu"))) for qr in quarters[:N_PERIODS]))
            if np.isfinite(gm) and gm > 0:
                game_mu_total = float(gm)
    except Exception:
        game_mu_total = None

    def _simulate_period(
        q: int,
        period_seconds: int,
        q_env_mult: float,
        q_pace_mult: float,
        blowout: bool,
        start_remaining: Optional[int] = None,
        first_offense_home: Optional[bool] = None,
        first_h_line: Optional[List[int]] = None,
        first_a_line: Optional[List[int]] = None,
    ) -> None:
        nonlocal home_score, away_score

        se_k = float(getattr(cfg, "score_effect_k", 0.0) or 0.0)

        def _score_effect(off_home: bool) -> float:
            # Score effect for the offense (Phase 2 #2). 1.0 exactly when k == 0, so the default path is unchanged.
            if se_k == 0.0:
                return 1.0
            if q > N_PERIODS:
                share = 1.0
            else:
                share = ((int(q) - 1) * float(quarter_seconds) + (float(quarter_seconds) - float(q_remaining))) / (float(N_PERIODS) * float(quarter_seconds))
                share = float(min(1.0, max(0.0, share)))
            tgt_margin = (float(target_home_points) - float(target_away_points)) if (target_home_points is not None and target_away_points is not None) else 0.0
            if not np.isfinite(tgt_margin):
                tgt_margin = 0.0
            lead = float(home_score - away_score) if off_home else float(away_score - home_score)
            expected = (tgt_margin if off_home else -tgt_margin) * share
            return float(np.clip(1.0 - se_k * (lead - expected), 0.85, 1.15))

        # RESUME: start_remaining is the clock left in a period already under way; None = the whole period, the
        # only value a pregame run ever passes (and then every expression below is the vendored one).
        period_left = int(period_seconds) if start_remaining is None else int(start_remaining)

        # Track an approximate game clock so we can bucket points into 3-minute intervals.
        # This is intentionally lightweight (we don't emit full timestamps per event).
        q_remaining = int(period_left)

        # possessions_per_game is per-team; our loop simulates team-possessions.
        base_poss = (2.0 * float(poss)) / float(N_PERIODS)
        # Scale possessions by the time to play relative to a full regulation period.
        base_poss *= float(period_left) / float(quarter_seconds)
        jitter = float(rng.normal(0.0, cfg.possessions_jitter))
        # The 6-possession floor is a full-period rule; a partial period may have none left.
        q_poss = int(max(6 if start_remaining is None else 0, round(base_poss * q_pace_mult * (1.0 + jitter))))

        for pidx in range(q_poss):
            if pidx == 0:
                offense_home = bool(rng.random() < 0.5) if first_offense_home is None else bool(first_offense_home)
            else:
                offense_home = not offense_home if bool(rng.random() < float(getattr(cfg, "possession_alternation", 0.85))) else bool(rng.random() < 0.5)

            margin_now = int(home_score - away_score)
            flags = _windows(q=int(q), period_seconds=int(period_seconds), q_remaining=int(q_remaining), margin=int(margin_now))
            home_context_w = _contextual_minutes_weights(
                h_mins,
                h_starter_scores,
                h_scorer_scores,
                flags=flags,
                team_is_trailing=bool(margin_now < 0),
                team_is_leading=bool(margin_now > 0),
                blowout=bool(blowout),
            )
            away_context_w = _contextual_minutes_weights(
                a_mins,
                a_starter_scores,
                a_scorer_scores,
                flags=flags,
                team_is_trailing=bool(margin_now > 0),
                team_is_leading=bool(margin_now < 0),
                blowout=bool(blowout),
            )

            if h_out_idx:
                home_context_w = np.asarray(home_context_w, dtype=float).copy()
                home_context_w[h_out_idx] = 0.0
            if a_out_idx:
                away_context_w = np.asarray(away_context_w, dtype=float).copy()
                away_context_w[a_out_idx] = 0.0

            use_contextual_lineups = bool(
                blowout
                or flags.get("opening_stint")
                or flags.get("bench_stint")
                or flags.get("mid_wave")
                or flags.get("closing_window")
                or flags.get("crunch_time")
                or flags.get("late_half_push")
                or flags.get("late_game_push")
            )

            h_line = None
            a_line = None
            if (not blowout) and (not use_contextual_lineups):
                h_line = _pick_lineup_from_pool(home_lineups, home_lineup_weights, n_players=len(home_players))
                a_line = _pick_lineup_from_pool(away_lineups, away_lineup_weights, n_players=len(away_players))
            if pidx == 0 and first_h_line:
                h_line = list(first_h_line)
            if pidx == 0 and first_a_line:
                a_line = list(first_a_line)
            if not h_line:
                h_line = sample_lineup(
                    rng,
                    home_players,
                    home_context_w,
                    k=5,
                    blowout_boost_bench=False,
                    bench_boost=cfg.bench_weight_boost,
                )
            if not a_line:
                a_line = sample_lineup(
                    rng,
                    away_players,
                    away_context_w,
                    k=5,
                    blowout_boost_bench=False,
                    bench_boost=cfg.bench_weight_boost,
                )

            # Possession may include multiple shot attempts on offensive rebounds.
            max_shots_this_poss = 5
            shot_n = 0

            while True:
                shot_n += 1

                margin_now = int(home_score - away_score)
                offense_trailing = bool(margin_now < 0) if offense_home else bool(margin_now > 0)
                offense_leading = bool(margin_now > 0) if offense_home else bool(margin_now < 0)

                # Approximate attempt duration (seconds). Keeps segment buckets plausible.
                try:
                    avg_sec = float(period_left) / float(max(1, q_poss))
                    avg_sec *= _contextual_duration_scale(
                        flags=flags,
                        team_is_trailing=bool(offense_trailing),
                        team_is_leading=bool(offense_leading),
                        blowout=bool(blowout),
                    )
                    dur = int(np.clip(rng.normal(avg_sec, 4.0), 4.0, 28.0))
                except Exception:
                    dur = 14

                # Segment indices at attempt end (approx) for scoring buckets.
                seg = 0
                minute_idx = 0
                q_remaining_after = int(q_remaining)
                try:
                    q_remaining_after = max(0, int(q_remaining - min(int(dur), int(q_remaining))))
                    q_elapsed_after = int(period_seconds - q_remaining_after)
                    seg = int(np.clip(q_elapsed_after // segment_seconds, 0, n_segments - 1))
                    minute_idx = int(np.clip(q_elapsed_after // minute_seconds, 0, n_minutes - 1))
                except Exception:
                    seg = 0
                    minute_idx = 0

                off_rates = h_rates if offense_home else a_rates
                p_tov = float(off_rates["p_tov"]) * (cfg.garbage_time_pace_scale if blowout else 1.0)
                p3 = float(off_rates["p3"])

                # Late-clock heuristics: 2-for-1 / trailing-team 3PA uptick.
                try:
                    is_reg = 1 <= int(q) <= N_PERIODS
                    close_game = (not blowout) and (abs(margin_now) <= 8)
                    is_2for1_window = is_reg and (int(q_remaining) <= 45) and (int(q_remaining) >= 24)
                    is_clutch = is_reg and (int(q_remaining) <= 60) and close_game and (int(q) in HALF_END)

                    if is_2for1_window:
                        p3 = float(np.clip(p3 + 0.02, 0.05, 0.70))
                    if (flags.get("late_half_push") or flags.get("late_game_push")) and offense_trailing:
                        bump = 0.03 if flags.get("late_half_push") else 0.05
                        if flags.get("crunch_time"):
                            bump += 0.02
                        p3 = float(np.clip(p3 + bump, 0.05, 0.78))
                    if flags.get("bench_stint") or flags.get("mid_wave"):
                        p3 = float(np.clip(p3 - 0.01, 0.05, 0.70))
                    if is_clutch and offense_trailing:
                        p3 = float(np.clip(p3 + 0.06, 0.05, 0.75))
                except Exception:
                    pass

                # Turnover ends the possession.
                if float(rng.random()) < p_tov:
                    if offense_home:
                        shooter_w = _usage_w(home_players, "_prior_tov_pm", h_line)
                        t_idx = int(_pick_weighted(rng, list(range(len(home_players))), shooter_w) or 0)
                        h["tov"][t_idx] += 1
                        if float(rng.random()) < cfg.base_steal_share_of_tov:
                            stl_w = _usage_w(away_players, "_prior_stl_pm", a_line)
                            s_idx = int(_pick_weighted(rng, list(range(len(away_players))), stl_w) or 0)
                            a["stl"][s_idx] += 1
                        if record_events:
                            events.append({"q": q, "type": "TOV", "off": "H", "player_i": t_idx})
                    else:
                        t_w = _usage_w(away_players, "_prior_tov_pm", a_line)
                        t_idx = int(_pick_weighted(rng, list(range(len(away_players))), t_w) or 0)
                        a["tov"][t_idx] += 1
                        if float(rng.random()) < cfg.base_steal_share_of_tov:
                            stl_w = _usage_w(home_players, "_prior_stl_pm", h_line)
                            s_idx = int(_pick_weighted(rng, list(range(len(home_players))), stl_w) or 0)
                            h["stl"][s_idx] += 1
                        if record_events:
                            events.append({"q": q, "type": "TOV", "off": "A", "player_i": t_idx})
                    try:
                        q_remaining = int(q_remaining_after)
                    except Exception:
                        pass
                    break

                shot_is_3 = bool(rng.random() < p3)
                points_if_make = 3 if shot_is_3 else 2

                foul_per_fga = float(off_rates["foul_per_fga"])
                nonshoot_pf = float(cfg.base_nonshooting_foul_per_poss)
                try:
                    is_reg = 1 <= int(q) <= N_PERIODS
                    close_game = (not blowout) and (abs(margin_now) <= 6)
                    if is_reg and (int(q) in HALF_END) and int(q_remaining) <= 45 and close_game:
                        # In close games late in Q2/Q4, the trailing defense is more likely to foul.
                        if offense_leading:
                            foul_per_fga = float(np.clip(foul_per_fga * 1.25, 0.0, 0.60))
                            nonshoot_pf = float(np.clip(nonshoot_pf + 0.10, 0.0, 0.60))
                    if close_game and offense_leading and (flags.get("late_half_push") or flags.get("late_game_push")):
                        foul_boost = 1.08 if flags.get("late_half_push") else 1.14
                        pf_boost = 0.04 if flags.get("late_half_push") else 0.06
                        foul_per_fga = float(np.clip(foul_per_fga * foul_boost, 0.0, 0.60))
                        nonshoot_pf = float(np.clip(nonshoot_pf + pf_boost, 0.0, 0.60))
                except Exception:
                    pass

                # Non-shooting foul noise (does not end the possession in this simplified model).
                do_nonshoot_pf = bool(rng.random() < nonshoot_pf)

                def _maybe_add_nonshoot_pf() -> None:
                    if not do_nonshoot_pf:
                        return
                    try:
                        if offense_home:
                            pf_w = _usage_w(away_players, "_prior_pf_pm", a_line)
                            didx = _pick_weighted(rng, list(range(len(away_players))), pf_w)
                            if didx is not None:
                                a["pf"][int(didx)] += 1
                        else:
                            pf_w = _usage_w(home_players, "_prior_pf_pm", h_line)
                            didx = _pick_weighted(rng, list(range(len(home_players))), pf_w)
                            if didx is not None:
                                h["pf"][int(didx)] += 1
                    except Exception:
                        return

                foul = bool(rng.random() < foul_per_fga) if not SHOOTER_FT_RATE else False

                if offense_home:
                    if shot_is_3:
                        w = _usage_w(home_players, "_prior_threes_att_pm", h_line)
                    else:
                        w = _usage_w(home_players, "_prior_fga_pm", h_line)
                    sh = int(_pick_weighted(rng, list(range(len(home_players))), w) or 0)
                    if SHOOTER_FT_RATE:
                        foul = bool(rng.random() < float(np.clip(foul_per_fga * float(h_ft_mult[sh]), 0.0, 0.95)))

                    h["fga"][sh] += 1
                    if shot_is_3:
                        h["fg3a"][sh] += 1

                    eff_scale = cfg.garbage_time_eff_scale if blowout else 1.0
                    base_p = float(h_3p_pct[sh] if shot_is_3 else h_fg_pct[sh])
                    make_p = float(np.clip(base_p * eff_scale * eff_mult_h * q_env_mult * _score_effect(True), 0.05, 0.95))
                    made = bool(rng.random() < make_p)

                    blk = False
                    if _blk_drawn(rng, shot_is_3, made, cfg.base_block_rate_on_2pa, a_blk_rate):
                        blk = True
                        blk_w = _usage_w(away_players, "_prior_blk_pm", a_line)
                        bidx = int(_pick_weighted(rng, list(range(len(away_players))), blk_w) or 0)
                        a["blk"][bidx] += 1

                    if made:
                        h["fgm"][sh] += 1
                        if shot_is_3:
                            h["fg3m"][sh] += 1
                            _add_q_stat(hq["threes"], q, sh, 1)
                        h["pts"][sh] += points_if_make
                        _add_q_stat(hq["pts"], q, sh, int(points_if_make))
                        home_score += points_if_make
                        _add_q_seg(home_q_seg_pts, q, seg, int(points_if_make))
                        _add_q_min(home_q_min_pts, q, minute_idx, int(points_if_make))

                        if rng.random() < 0.58:
                            ast_w = _usage_w(home_players, "_prior_ast_pm", [i for i in h_line if i != sh])
                            aidx = _pick_weighted(rng, list(range(len(home_players))), ast_w)
                            if aidx is not None:
                                h["ast"][int(aidx)] += 1
                                _add_q_stat(hq["ast"], q, int(aidx), 1)

                        if foul and rng.random() < 0.32:
                            h["fta"][sh] += 1
                            ftp = float(np.clip(float(h_ft_pct[sh]) * eff_mult_h * q_env_mult * _score_effect(True), 0.45, 0.95))
                            if rng.random() < ftp:
                                h["ftm"][sh] += 1
                                h["pts"][sh] += 1
                                _add_q_stat(hq["pts"], q, sh, 1)
                                home_score += 1
                                _add_q_seg(home_q_seg_pts, q, seg, 1)
                                _add_q_min(home_q_min_pts, q, minute_idx, 1)
                            pf_w = _usage_w(away_players, "_prior_pf_pm", a_line)
                            didx = _pick_weighted(rng, list(range(len(away_players))), pf_w)
                            if didx is not None:
                                a["pf"][int(didx)] += 1
                        _maybe_add_nonshoot_pf()
                        if record_events:
                            events.append({"q": q, "type": "FGM3" if shot_is_3 else "FGM2", "off": "H", "sh": sh, "pts": points_if_make})
                        try:
                            q_remaining = int(q_remaining_after)
                        except Exception:
                            pass
                        break

                    if foul and rng.random() < 0.70:
                        n_ft = 3 if shot_is_3 else 2
                        if FOULED_MISS_NOT_FGA:
                            h["fga"][sh] -= 1
                            if shot_is_3:
                                h["fg3a"][sh] -= 1
                        h["fta"][sh] += int(n_ft)
                        ftp = float(np.clip(float(h_ft_pct[sh]) * eff_mult_h * q_env_mult * _score_effect(True), 0.45, 0.95))
                        made_fts = int(rng.binomial(int(n_ft), ftp))
                        if made_fts > 0:
                            h["ftm"][sh] += made_fts
                            h["pts"][sh] += made_fts
                            _add_q_stat(hq["pts"], q, sh, int(made_fts))
                            home_score += made_fts
                            _add_q_seg(home_q_seg_pts, q, seg, int(made_fts))
                            _add_q_min(home_q_min_pts, q, minute_idx, int(made_fts))
                        pf_w = _usage_w(away_players, "_prior_pf_pm", a_line)
                        didx = _pick_weighted(rng, list(range(len(away_players))), pf_w)
                        if didx is not None:
                            a["pf"][int(didx)] += 1
                        _maybe_add_nonshoot_pf()
                        if record_events:
                            events.append({"q": q, "type": "FTA", "off": "H", "sh": sh, "fta": n_ft, "ftm": made_fts})
                        try:
                            q_remaining = int(q_remaining_after)
                        except Exception:
                            pass
                        break

                    try:
                        oreb_rate = float(cfg.base_oreb_rate) * (float(oreb_mult_h) if offense_home else float(oreb_mult_a))
                        oreb_rate = float(np.clip(oreb_rate, 0.05, 0.55))
                    except Exception:
                        oreb_rate = float(cfg.base_oreb_rate)
                    oreb = bool(rng.random() < oreb_rate)
                    if oreb:
                        reb_w = _usage_w(home_players, "_prior_reb_pm", h_line)
                        ridx = _pick_weighted(rng, list(range(len(home_players))), reb_w)
                        if ridx is not None and _reb_credited(rng, bool(oreb)):
                            h["reb"][int(ridx)] += 1
                            _add_q_stat(hq["reb"], q, int(ridx), 1)
                    else:
                        reb_w = _usage_w(away_players, "_prior_reb_pm", a_line)
                        ridx = _pick_weighted(rng, list(range(len(away_players))), reb_w)
                        if ridx is not None and _reb_credited(rng, bool(oreb)):
                            a["reb"][int(ridx)] += 1
                            _add_q_stat(aq["reb"], q, int(ridx), 1)
                    if record_events:
                        events.append({"q": q, "type": "MISS3" if shot_is_3 else "MISS2", "off": "H", "sh": sh, "blk": blk})
                    try:
                        q_remaining = int(q_remaining_after)
                    except Exception:
                        pass
                    _maybe_add_nonshoot_pf()
                    if oreb and (shot_n < int(max_shots_this_poss)) and int(q_remaining) > 0:
                        continue
                    break

                else:
                    if shot_is_3:
                        w = _usage_w(away_players, "_prior_threes_att_pm", a_line)
                    else:
                        w = _usage_w(away_players, "_prior_fga_pm", a_line)
                    sh = int(_pick_weighted(rng, list(range(len(away_players))), w) or 0)
                    if SHOOTER_FT_RATE:
                        foul = bool(rng.random() < float(np.clip(foul_per_fga * float(a_ft_mult[sh]), 0.0, 0.95)))

                    a["fga"][sh] += 1
                    if shot_is_3:
                        a["fg3a"][sh] += 1

                    eff_scale = cfg.garbage_time_eff_scale if blowout else 1.0
                    base_p = float(a_3p_pct[sh] if shot_is_3 else a_fg_pct[sh])
                    make_p = float(np.clip(base_p * eff_scale * eff_mult_a * q_env_mult * _score_effect(False), 0.05, 0.95))
                    made = bool(rng.random() < make_p)

                    blk = False
                    if _blk_drawn(rng, shot_is_3, made, cfg.base_block_rate_on_2pa, h_blk_rate):
                        blk = True
                        blk_w = _usage_w(home_players, "_prior_blk_pm", h_line)
                        bidx = int(_pick_weighted(rng, list(range(len(home_players))), blk_w) or 0)
                        h["blk"][bidx] += 1

                    if made:
                        a["fgm"][sh] += 1
                        if shot_is_3:
                            a["fg3m"][sh] += 1
                            _add_q_stat(aq["threes"], q, sh, 1)
                        a["pts"][sh] += points_if_make
                        _add_q_stat(aq["pts"], q, sh, int(points_if_make))
                        away_score += points_if_make
                        _add_q_seg(away_q_seg_pts, q, seg, int(points_if_make))
                        _add_q_min(away_q_min_pts, q, minute_idx, int(points_if_make))

                        if rng.random() < 0.58:
                            ast_w = _usage_w(away_players, "_prior_ast_pm", [i for i in a_line if i != sh])
                            aidx = _pick_weighted(rng, list(range(len(away_players))), ast_w)
                            if aidx is not None:
                                a["ast"][int(aidx)] += 1
                                _add_q_stat(aq["ast"], q, int(aidx), 1)

                        if foul and rng.random() < 0.32:
                            a["fta"][sh] += 1
                            ftp = float(np.clip(float(a_ft_pct[sh]) * eff_mult_a * q_env_mult * _score_effect(False), 0.45, 0.95))
                            if rng.random() < ftp:
                                a["ftm"][sh] += 1
                                a["pts"][sh] += 1
                                _add_q_stat(aq["pts"], q, sh, 1)
                                away_score += 1
                                _add_q_seg(away_q_seg_pts, q, seg, 1)
                                _add_q_min(away_q_min_pts, q, minute_idx, 1)
                            pf_w = _usage_w(home_players, "_prior_pf_pm", h_line)
                            didx = _pick_weighted(rng, list(range(len(home_players))), pf_w)
                            if didx is not None:
                                h["pf"][int(didx)] += 1
                        _maybe_add_nonshoot_pf()
                        if record_events:
                            events.append({"q": q, "type": "FGM3" if shot_is_3 else "FGM2", "off": "A", "sh": sh, "pts": points_if_make})
                        try:
                            q_remaining = int(q_remaining_after)
                        except Exception:
                            pass
                        break

                    if foul and rng.random() < 0.70:
                        n_ft = 3 if shot_is_3 else 2
                        if FOULED_MISS_NOT_FGA:
                            a["fga"][sh] -= 1
                            if shot_is_3:
                                a["fg3a"][sh] -= 1
                        a["fta"][sh] += int(n_ft)
                        ftp = float(np.clip(float(a_ft_pct[sh]) * eff_mult_a * q_env_mult * _score_effect(False), 0.45, 0.95))
                        made_fts = int(rng.binomial(int(n_ft), ftp))
                        if made_fts > 0:
                            a["ftm"][sh] += made_fts
                            a["pts"][sh] += made_fts
                            _add_q_stat(aq["pts"], q, sh, int(made_fts))
                            away_score += made_fts
                            _add_q_seg(away_q_seg_pts, q, seg, int(made_fts))
                            _add_q_min(away_q_min_pts, q, minute_idx, int(made_fts))
                        pf_w = _usage_w(home_players, "_prior_pf_pm", h_line)
                        didx = _pick_weighted(rng, list(range(len(home_players))), pf_w)
                        if didx is not None:
                            h["pf"][int(didx)] += 1
                        _maybe_add_nonshoot_pf()
                        if record_events:
                            events.append({"q": q, "type": "FTA", "off": "A", "sh": sh, "fta": n_ft, "ftm": made_fts})
                        try:
                            q_remaining = int(q_remaining_after)
                        except Exception:
                            pass
                        break

                    try:
                        oreb_rate = float(cfg.base_oreb_rate) * (float(oreb_mult_h) if offense_home else float(oreb_mult_a))
                        oreb_rate = float(np.clip(oreb_rate, 0.05, 0.55))
                    except Exception:
                        oreb_rate = float(cfg.base_oreb_rate)
                    oreb = bool(rng.random() < oreb_rate)
                    if oreb:
                        reb_w = _usage_w(away_players, "_prior_reb_pm", a_line)
                        ridx = _pick_weighted(rng, list(range(len(away_players))), reb_w)
                        if ridx is not None and _reb_credited(rng, bool(oreb)):
                            a["reb"][int(ridx)] += 1
                            _add_q_stat(aq["reb"], q, int(ridx), 1)
                    else:
                        reb_w = _usage_w(home_players, "_prior_reb_pm", h_line)
                        ridx = _pick_weighted(rng, list(range(len(home_players))), reb_w)
                        if ridx is not None and _reb_credited(rng, bool(oreb)):
                            h["reb"][int(ridx)] += 1
                            _add_q_stat(hq["reb"], q, int(ridx), 1)
                    if record_events:
                        events.append({"q": q, "type": "MISS3" if shot_is_3 else "MISS2", "off": "A", "sh": sh, "blk": blk})
                    try:
                        q_remaining = int(q_remaining_after)
                    except Exception:
                        pass
                    _maybe_add_nonshoot_pf()
                    if oreb and (shot_n < int(max_shots_this_poss)) and int(q_remaining) > 0:
                        continue
                    break


    for q in range(1, N_PERIODS + 1):
        if q < start_period:
            # RESUME: a period already played contributes its real points and makes no draws.
            home_q_pts.append(_state_pts(state.home_period_pts, q))
            away_q_pts.append(_state_pts(state.away_period_pts, q))
            continue
        h_start = int(home_score)
        a_start = int(away_score)
        resuming_here = bool(q == start_period and not opening_tip)
        if resuming_here:
            # This period's points so far belong to it (the score already includes them).
            h_start -= _state_pts(state.home_period_pts, q)
            a_start -= _state_pts(state.away_period_pts, q)

        # Quarter-level environment multiplier derived from quarter-model mean/volatility.
        # - Mean shift nudges expected scoring toward the quarter model's mean split
        # - Random component adds quarter-to-quarter swings
        # This keeps the simulation fully possession-driven (no point reconciliation).
        q_env_mult = 1.0
        q_pace_mult = 1.0
        try:
            if quarters and len(quarters) >= q:
                qr = quarters[q - 1]
                hm = float(getattr(qr, "home_pts_mu", (qr or {}).get("home_pts_mu")))
                am = float(getattr(qr, "away_pts_mu", (qr or {}).get("away_pts_mu")))
                hs = float(getattr(qr, "home_pts_sigma", (qr or {}).get("home_pts_sigma")))
                as_ = float(getattr(qr, "away_pts_sigma", (qr or {}).get("away_pts_sigma")))
                corr = float(getattr(qr, "corr", (qr or {}).get("corr", 0.0)))
                tot_mu = max(1.0, float(hm + am))
                tot_sd = float(np.sqrt(max(0.0, hs * hs + as_ * as_ + 2.0 * corr * hs * as_)))
                sd_frac = float(np.clip(tot_sd / tot_mu, 0.02, 0.25))

                # Mean shift: align expected quarter total to quarter-model split.
                q_mu_mult = 1.0
                if game_mu_total is not None and game_mu_total > 0:
                    base_q = float(game_mu_total) / float(N_PERIODS)
                    if base_q > 0:
                        q_mu_mult = float(np.clip(tot_mu / base_q, 0.88, 1.12))

                # Split mean shift into pace + efficiency components.
                # (Points ~ possessions * PPP), so sqrt split is a decent neutral choice.
                q_pace_mult = float(np.clip(np.sqrt(q_mu_mult), 0.94, 1.06))
                q_eff_mu_mult = float(np.clip(np.sqrt(q_mu_mult), 0.94, 1.06))

                # Random env: scale down slightly to avoid over-dispersion.
                q_sd_mult = float(np.clip(1.0 + rng.normal(0.0, sd_frac * float(getattr(cfg, "env_sd_scale", 0.65))), 0.85, 1.20))
                q_env_mult = float(np.clip(q_eff_mu_mult * q_sd_mult, 0.82, 1.22))
        except Exception:
            q_env_mult = 1.0
            q_pace_mult = 1.0

        # For regulation periods, enforce a slightly higher minimum possessions.
        # (OT periods will use a lower min via _simulate_period())
        q_pace_mult = float(q_pace_mult)

        margin = int(home_score - away_score)
        blowout = False
        if q >= N_PERIODS and abs(margin) >= int(cfg.blowout_q4_margin):
            blowout = True
        if q >= int(lp.second_half_first_period) and abs(margin) >= int(cfg.blowout_margin):
            blowout = True

        if resuming_here:
            _simulate_period(q=q, period_seconds=int(quarter_seconds), q_env_mult=float(q_env_mult), q_pace_mult=float(q_pace_mult), blowout=bool(blowout), **resume_kwargs)
        else:
            _simulate_period(q=q, period_seconds=int(quarter_seconds), q_env_mult=float(q_env_mult), q_pace_mult=float(q_pace_mult), blowout=bool(blowout))

        home_q_pts.append(int(home_score - h_start))
        away_q_pts.append(int(away_score - a_start))

    # Overtime: simulate 5-minute periods until a winner (up to a safety cap)
    try:
        ot_n = 0
        resume_in_ot = bool(start_period > N_PERIODS)
        if resume_in_ot:
            # RESUME in overtime: earlier overtimes were played; record them without draws.
            for p_done in range(N_PERIODS + 1, start_period):
                home_ot_pts.append(_state_pts(state.home_period_pts, p_done))
                away_ot_pts.append(_state_pts(state.away_period_pts, p_done))
                ot_n += 1
        while resume_in_ot or (int(home_score) == int(away_score) and ot_n < int(max_overtimes)):
            ot_n += 1
            h_start = int(home_score)
            a_start = int(away_score)

            # Reuse last-known environment; keep it stable for OT.
            if resume_in_ot:
                resume_in_ot = False
                h_start -= _state_pts(state.home_period_pts, N_PERIODS + int(ot_n))
                a_start -= _state_pts(state.away_period_pts, N_PERIODS + int(ot_n))
                _simulate_period(q=N_PERIODS + int(ot_n), period_seconds=int(ot_seconds), q_env_mult=1.0, q_pace_mult=1.0, blowout=False, **resume_kwargs)
            else:
                _simulate_period(q=N_PERIODS + int(ot_n), period_seconds=int(ot_seconds), q_env_mult=1.0, q_pace_mult=1.0, blowout=False)

            home_ot_pts.append(int(home_score - h_start))
            away_ot_pts.append(int(away_score - a_start))
    except Exception:
        pass

    def finalize(players: pd.DataFrame, agg: Dict[str, np.ndarray], qagg: Dict[str, np.ndarray]) -> Dict[str, Any]:
        out_players: List[Dict[str, Any]] = []
        mins = _safe_series(players, "_sim_min").to_numpy(dtype=float)
        names = [str(x or "").strip() for x in players.get("player_name", pd.Series([""] * len(players)))].copy()
        for i in range(len(players)):
            out_players.append(
                {
                    "player_name": names[i],
                    "min": float(mins[i]) if np.isfinite(mins[i]) else None,
                    "pts": int(agg["pts"][i]),
                    "q_pts": [int(qagg["pts"][k, i]) for k in range(N_PERIODS)],
                    "reb": int(agg["reb"][i]),
                    "q_reb": [int(qagg["reb"][k, i]) for k in range(N_PERIODS)],
                    "ast": int(agg["ast"][i]),
                    "q_ast": [int(qagg["ast"][k, i]) for k in range(N_PERIODS)],
                    "threes": int(agg["fg3m"][i]),
                    "q_threes": [int(qagg["threes"][k, i]) for k in range(N_PERIODS)],
                    "fg3a": int(agg["fg3a"][i]),
                    "fg3m": int(agg["fg3m"][i]),
                    "fga": int(agg["fga"][i]),
                    "fgm": int(agg["fgm"][i]),
                    "fta": int(agg["fta"][i]),
                    "ftm": int(agg["ftm"][i]),
                    "pf": int(agg["pf"][i]),
                    "stl": int(agg["stl"][i]),
                    "blk": int(agg["blk"][i]),
                    "tov": int(agg["tov"][i]),
                }
            )

        out_players.sort(key=lambda r: ((r.get("min") or 0.0), r.get("pts") or 0), reverse=True)
        return {
            "players": out_players,
            "team_total_pts": int(sum(int(p.get("pts") or 0) for p in out_players)),
            "team_total_reb": int(sum(int(p.get("reb") or 0) for p in out_players)),
            "team_total_ast": int(sum(int(p.get("ast") or 0) for p in out_players)),
            "team_total_threes": int(sum(int(p.get("threes") or 0) for p in out_players)),
            "team_total_fg3a": int(sum(int(p.get("fg3a") or 0) for p in out_players)),
            "team_total_fga": int(sum(int(p.get("fga") or 0) for p in out_players)),
            "team_total_fgm": int(sum(int(p.get("fgm") or 0) for p in out_players)),
            "team_total_fta": int(sum(int(p.get("fta") or 0) for p in out_players)),
            "team_total_ftm": int(sum(int(p.get("ftm") or 0) for p in out_players)),
            "team_total_pf": int(sum(int(p.get("pf") or 0) for p in out_players)),
            "team_total_tov": int(sum(int(p.get("tov") or 0) for p in out_players)),
            "team_total_stl": int(sum(int(p.get("stl") or 0) for p in out_players)),
            "team_total_blk": int(sum(int(p.get("blk") or 0) for p in out_players)),
        }

    home_box = finalize(home_players, h, hq)
    away_box = finalize(away_players, a, aq)
    home_box["events"] = (events[:500] if record_events else [])
    away_box["events"] = []

    # Segment points per quarter (4x4 and 4x12). Helpful for live-lens interval ladders.
    try:
        home_box["q_segment_pts"] = home_q_seg_pts.astype(int).tolist()
        away_box["q_segment_pts"] = away_q_seg_pts.astype(int).tolist()
        home_box["segment_seconds"] = int(segment_seconds)
        away_box["segment_seconds"] = int(segment_seconds)

        home_box["q_minute_pts"] = home_q_min_pts.astype(int).tolist()
        away_box["q_minute_pts"] = away_q_min_pts.astype(int).tolist()
        home_box["minute_seconds"] = int(minute_seconds)
        away_box["minute_seconds"] = int(minute_seconds)
    except Exception:
        pass

    # Overtime totals per OT period (per-team).
    try:
        if home_ot_pts or away_ot_pts:
            home_box["ot_pts"] = [int(x) for x in (home_ot_pts or [])]
            away_box["ot_pts"] = [int(x) for x in (away_ot_pts or [])]
            home_box["ot_seconds"] = int(ot_seconds)
            away_box["ot_seconds"] = int(ot_seconds)
    except Exception:
        pass

    return home_box, away_box, home_q_pts, away_q_pts


def _state_pts(period_pts: Tuple[int, ...], period: int) -> int:
    """Points a GameState records for a 1-based period; 0 for a period it has no entry for."""
    k = int(period) - 1
    return int(period_pts[k]) if 0 <= k < len(period_pts) else 0


def _player_names(players: pd.DataFrame) -> List[str]:
    return [str(x or "").strip() for x in players.get("player_name", pd.Series([""] * len(players)))]


def _lineup_indices(names: List[str], on_floor: Tuple[str, ...], *, side: str) -> Optional[List[int]]:
    """Indices of the live five in the player frame. A name not in the frame REFUSES (ValueError), never drops."""
    if not on_floor:
        return None
    index = {nm: i for i, nm in enumerate(names)}
    missing = [str(nm) for nm in on_floor if str(nm).strip() not in index]
    if missing:
        raise ValueError(f"GameState.{side}_on_floor names players not in the {side} player frame: {missing}")
    return [index[str(nm).strip()] for nm in on_floor]


def _drop_lineups_with(
    lineups: Optional[List[List[int]]], weights: Optional[np.ndarray], out: set
) -> Tuple[Optional[List[List[int]]], Optional[np.ndarray]]:
    """The lineup pool without any unit that contains a fouled-out player (weights kept aligned)."""
    if not lineups:
        return lineups, weights
    keep = [i for i, lu in enumerate(lineups) if not (set(int(x) for x in (lu or [])) & out)]
    w = None
    if weights is not None:
        arr = np.asarray(weights, dtype=float)
        w = np.asarray([arr[i] if i < arr.size else 1.0 for i in keep], dtype=float)
    return [lineups[i] for i in keep], w
