"""Fetch and cache the full NFL regular-season schedule for one season from
nflverse's public schedule dataset (github.com/nflverse/nfldata).

Writes data/nfl_source/schedule_{season}.csv -- schedule ingestion only, per
the 2026 season bootstrap plan. This does not wire into NFL's picks/cards
display: that reads from upcoming_recs_*.csv, which is generated by the
separate, complex NFL-Betting/nfl_compare pipeline this script intentionally
does not touch (see smartsim_ats_policy_implementation_report.md-adjacent
2026 bootstrap plan for why that's out of scope here).

Usage:
    python scripts/fetch_nfl_schedule.py --season 2026
"""

from __future__ import annotations

import argparse
import csv
import io
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from syndicate.features.nfl.sources import default_nfl_source_root  # noqa: E402

NFLVERSE_GAMES_URL = "https://raw.githubusercontent.com/nflverse/nfldata/master/data/games.csv"

SCHEDULE_COLUMNS: tuple[str, ...] = (
    "game_id",
    "season",
    "game_type",
    "week",
    "gameday",
    "gametime",
    "away_team",
    "home_team",
    "away_score",
    "home_score",
    "spread_line",
    "total_line",
    "away_moneyline",
    "home_moneyline",
    "stadium",
)


def fetch_nflverse_games() -> list[dict[str, str]]:
    request = urllib.request.Request(NFLVERSE_GAMES_URL, headers={"User-Agent": "syndicate-nfl-schedule/1.0"})
    with urllib.request.urlopen(request, timeout=30) as response:
        text = response.read().decode("utf-8-sig")
    return list(csv.DictReader(io.StringIO(text)))


def schedule_path(season: int, *, source_root: Path | None = None) -> Path:
    root = source_root if source_root is not None else default_nfl_source_root()
    return root / f"schedule_{season}.csv"


def filter_season_games(all_games: list[dict[str, str]], season: int) -> list[dict[str, str]]:
    return [row for row in all_games if row.get("season") == str(season) and row.get("game_type") == "REG"]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--season", type=int, required=True)
    args = parser.parse_args()

    all_games = fetch_nflverse_games()
    season_games = filter_season_games(all_games, args.season)

    path = schedule_path(args.season)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=SCHEDULE_COLUMNS, extrasaction="ignore")
        writer.writeheader()
        for row in season_games:
            writer.writerow({column: row.get(column, "") for column in SCHEDULE_COLUMNS})

    weeks = sorted({int(row["week"]) for row in season_games if row.get("week")})
    print(f"games_written={len(season_games)}")
    print(f"weeks={weeks}")
    print(f"schedule_path={path}")


if __name__ == "__main__":
    main()
