"""Regenerate ``syndicate/features/basketball_engine/engine.py`` from the vendored NBA engine.

ONE-SHOT PORT TOOL (lane basketball-native-engine, 2026-10-09). It keeps a
record of HOW the native engine was derived, so a reviewer can check every
change against the vendored source instead of trusting a 2,200-line
hand-copy. It applies anchored replacements to
``vendor/nba_betting_repo/src/nba_betting/sim/events.py``. Every anchor must
match an exact, expected number of times, or the tool aborts and writes
nothing.

The edits fall in three groups:
  1. module switches and league constants -> ``LeagueParams`` fields, bound to
     the SAME local names inside the simulators, so the loop body is textually
     unchanged;
  2. ``_sample_lineup`` -> a ``sample_lineup`` PARAMETER (no monkey-patched
     global);
  3. the RESUME hooks (``GameState``). Each one reduces to the original
     expression when ``state`` is the opening tip.

Once the switch has landed, engine.py is the source of truth and this tool is
history. Re-running it would DISCARD any later native edit. ``--check`` diffs
the regenerated text against the file on disk and exits 1 on a difference.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "vendor" / "nba_betting_repo" / "src" / "nba_betting" / "sim" / "events.py"
DST = ROOT / "syndicate" / "features" / "basketball_engine" / "engine.py"

HEADER = '''"""Syndicate's basketball possession engine: ONE league-parametric engine (nba, wnba; ncaab hooks).

Ported 2026-10-09 (lane basketball-native-engine, plan P1:
docs/ai_context/basketball_live_native_plan.md) from
vendor/nba_betting_repo/src/nba_betting/sim/events.py (and its WNBA twin),
which this module REPLACES at runtime. Generated by
scripts/port_basketball_engine.py; the loop body is the vendored text.

What changed against the vendored engines, and nothing else:
  * The module-level switches (SHOOTER_FT_RATE, BLOCK_MODE, ...) and the WNBA
    ``LEAGUE`` constants are ``LeagueParams`` fields (``league.py``). Inside the
    simulators they bind to the SAME local names, so the per-possession code is
    the vendored code.
  * Lineup sampling is the ``sample_lineup`` PARAMETER. Syndicate used to patch
    the vendored module's ``_sample_lineup`` global for the duration of a call.
  * ``simulate_pbp_game_boxscore`` takes ``state=GameState(...)`` and resumes
    from a live situation (``resume.py``). ``GameState()`` is the opening tip:
    the same draws and the same output as the pregame run.
  * The period count is a parameter (2 halves for NCAAB), and every
    quarter-shaped rule is written in terms of halves, which reduces to the
    old (1, 3) / (2, 4) / 4 for quarters.

PARITY: scripts/basketball_engine_parity.py replays a recorded corpus of REAL
production per-draw inputs through this engine and through the vendored one,
seed for seed. The switch in basketball_props_smart_sim.py was gated on 0
mismatches.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import partial
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from .league import LeagueParams
from .resume import GameState, _fouled_out_names

'''

# (anchor, replacement, expected count[, scope]). Applied in order; each must match exactly `count` times within its
# scope: "all" (default), or "pbp" (only the text from `def simulate_pbp_game_boxscore(` on) for an anchor the legacy
# event-level simulator repeats verbatim.
EDITS: list[tuple[str, str, int]] = [
    # ---- header -------------------------------------------------------------------------------------------
    (
        "from __future__ import annotations\n\nfrom dataclasses import dataclass\nfrom typing import Any, Dict, List, Optional, Tuple\n\nimport numpy as np\nimport pandas as pd\n\n\n",
        "",
        1,
    ),
    # ---- _sample_lineup is the DEFAULT sampler now, not a patched global -----------------------------------
    ("def _sample_lineup(\n", "def sample_lineup_minutes_weighted(\n", 1),
    # ---- rotation windows: halves, not hardcoded quarters ---------------------------------------------------
    (
        "def _rotation_windows(q: int, period_seconds: int, q_remaining: int, margin: int) -> Dict[str, bool]:\n"
        "    qi = int(q)\n"
        "    rem = max(0, int(q_remaining))\n"
        "    elapsed = max(0, int(period_seconds) - rem)\n"
        "    abs_margin = abs(int(margin))\n"
        "    is_reg = 1 <= qi <= 4\n"
        "    return {\n"
        '        "opening_stint": bool(is_reg and qi in (1, 3) and elapsed < 180),\n'
        '        "bench_stint": bool(is_reg and qi in (2, 4) and elapsed < 180),\n'
        '        "mid_wave": bool(is_reg and qi in (1, 3) and 180 <= elapsed < 420),\n'
        '        "closing_window": bool(is_reg and qi in (2, 4) and rem <= 210 and abs_margin <= 10),\n'
        '        "crunch_time": bool(is_reg and qi == 4 and rem <= 180 and abs_margin <= 8),\n'
        '        "late_half_push": bool(is_reg and qi == 2 and rem <= 90 and abs_margin <= 12),\n'
        '        "late_game_push": bool(is_reg and qi == 4 and rem <= 180 and abs_margin <= 14),\n'
        "    }\n",
        "def _rotation_windows(q: int, period_seconds: int, q_remaining: int, margin: int, *, lp: LeagueParams) -> Dict[str, bool]:\n"
        "    # Quarters: half starts (1, 3), half ends (2, 4), last 4, first-half end 2 -- exactly the vendored literals.\n"
        "    # The second-by-second thresholds are the vendored NBA values in every league (P3/P4 own any re-fit).\n"
        "    qi = int(q)\n"
        "    rem = max(0, int(q_remaining))\n"
        "    elapsed = max(0, int(period_seconds) - rem)\n"
        "    abs_margin = abs(int(margin))\n"
        "    last = int(lp.regulation_periods)\n"
        "    half_start = lp.half_start_periods\n"
        "    half_end = lp.half_end_periods\n"
        "    first_half_end = half_end[0]\n"
        "    is_reg = 1 <= qi <= last\n"
        "    return {\n"
        '        "opening_stint": bool(is_reg and qi in half_start and elapsed < 180),\n'
        '        "bench_stint": bool(is_reg and qi in half_end and elapsed < 180),\n'
        '        "mid_wave": bool(is_reg and qi in half_start and 180 <= elapsed < 420),\n'
        '        "closing_window": bool(is_reg and qi in half_end and rem <= 210 and abs_margin <= 10),\n'
        '        "crunch_time": bool(is_reg and qi == last and rem <= 180 and abs_margin <= 8),\n'
        '        "late_half_push": bool(is_reg and qi == first_half_end and qi != last and rem <= 90 and abs_margin <= 12),\n'
        '        "late_game_push": bool(is_reg and qi == last and rem <= 180 and abs_margin <= 14),\n'
        "    }\n",
        1,
    ),
    # ---- team rates: league minutes and possession floor ----------------------------------------------------
    (
        'def _team_rates_from_priors(players: pd.DataFrame, cfg: EventSimConfig) -> Dict[str, float]:',
        'def _team_rates_from_priors(players: pd.DataFrame, cfg: EventSimConfig, *, lp: LeagueParams) -> Dict[str, float]:',
        1,
    ),
    ("        total_min = 240.0\n", "        total_min = float(lp.regulation_team_minutes)\n", 1),
    ("    poss = max(60.0, float(cfg.possessions_per_game))\n", "    poss = max(float(lp.min_rate_possessions), float(cfg.possessions_per_game))\n", 1),
    # ---- block rate / block draw / rebound credit / usage weights take the league -------------------------
    (
        "def _team_block_rate_on_missed_2pa(def_players: pd.DataFrame, def_mins: np.ndarray, off_players: pd.DataFrame, off_mins: np.ndarray, off_rates: Dict[str, float], off_fg_pct: np.ndarray, off_eff: float, possessions: float, oreb: float, ft_mult: Optional[np.ndarray] = None) -> float:",
        "def _team_block_rate_on_missed_2pa(def_players: pd.DataFrame, def_mins: np.ndarray, off_players: pd.DataFrame, off_mins: np.ndarray, off_rates: Dict[str, float], off_fg_pct: np.ndarray, off_eff: float, possessions: float, oreb: float, ft_mult: Optional[np.ndarray] = None, *, lp: LeagueParams) -> float:",
        1,
    ),
    ("fg3=float(BLOCK_RATE_ASSUMED_FG3_PCT) * float(off_eff)", "fg3=float(lp.block_rate_assumed_fg3_pct) * float(off_eff)", 1),
    ("            return LEAGUE_BLOCKS_PER_MISSED_2PA\n", "            return lp.league_blocks_per_missed_2pa\n", 1),
    ("        return LEAGUE_BLOCKS_PER_MISSED_2PA\n", "        return lp.league_blocks_per_missed_2pa\n", 1),
    (
        "def _block_drawn(rng: np.random.Generator, shot_is_3: bool, made: bool, legacy_rate: float, rate_on_missed_2pa: float) -> bool:\n    if BLOCK_MODE == \"legacy\":",
        "def _block_drawn(rng: np.random.Generator, shot_is_3: bool, made: bool, legacy_rate: float, rate_on_missed_2pa: float, *, lp: LeagueParams) -> bool:\n    if lp.block_mode == \"legacy\":",
        1,
    ),
    (
        "def _player_rebound_credited(rng: np.random.Generator, offensive: bool) -> bool:\n    if not PLAYER_REBOUND_CREDIT:\n        return True  # no draw: the old credit-every-miss path\n    p = OREB_PLAYER_CREDIT if offensive else DREB_PLAYER_CREDIT\n",
        "def _player_rebound_credited(rng: np.random.Generator, offensive: bool, *, lp: LeagueParams) -> bool:\n    if not lp.player_rebound_credit:\n        return True  # no draw: the old credit-every-miss path\n    p = lp.oreb_player_credit if offensive else lp.dreb_player_credit\n",
        1,
    ),
    (
        "def _player_usage_weights(players: pd.DataFrame, col_pm: str, lineup_idx: List[int]) -> np.ndarray:",
        "def _player_usage_weights(players: pd.DataFrame, col_pm: str, lineup_idx: List[int], *, lp: LeagueParams) -> np.ndarray:",
        1,
    ),
    ("    if BLOCK_ALLOC_BY_RATE and col_pm == \"_prior_blk_pm\":", "    if lp.block_alloc_by_rate and col_pm == \"_prior_blk_pm\":", 1),
    ("        line = np.maximum(pm[idx], BLOCK_ALLOC_FLOOR_PM)", "        line = np.maximum(pm[idx], lp.block_alloc_floor_pm)", 1),
    # ---- PBP simulator signature ----------------------------------------------------------------------------
    (
        "    away_team_adj: Optional[Dict[str, float]] = None,\n) -> Tuple[Dict[str, Any], Dict[str, Any], List[int], List[int]]:\n",
        "    away_team_adj: Optional[Dict[str, float]] = None,\n    *,\n    league: LeagueParams,\n    sample_lineup: Optional[Callable[..., List[int]]] = None,\n    state: Optional[GameState] = None,\n) -> Tuple[Dict[str, Any], Dict[str, Any], List[int], List[int]]:\n",
        1,
    ),
    # Both simulators open with `cfg = cfg or EventSimConfig()`. The default config takes the league's pace (the
    # WNBA EventSimConfig default was LEAGUE.baseline_pace), and every switch binds to its vendored local name.
    (
        "    cfg = cfg or EventSimConfig()\n",
        "    lp = league\n"
        "    cfg = cfg or EventSimConfig(possessions_per_game=float(lp.default_possessions_per_game))\n"
        "    sample_lineup = sample_lineup or sample_lineup_minutes_weighted\n"
        "    _usage_w = partial(_player_usage_weights, lp=lp)\n"
        "    _rates = partial(_team_rates_from_priors, lp=lp)\n"
        "    _windows = partial(_rotation_windows, lp=lp)\n"
        "    _blk_drawn = partial(_block_drawn, lp=lp)\n"
        "    _reb_credited = partial(_player_rebound_credited, lp=lp)\n"
        "    SHOOTER_FT_RATE = bool(lp.shooter_ft_rate)\n"
        "    FOULED_MISS_NOT_FGA = bool(lp.fouled_miss_not_fga)\n"
        "    EXACT_TARGET_CALIBRATION = bool(lp.exact_target_calibration)\n"
        "    TOV_PER_ATTEMPT = bool(lp.tov_per_attempt)\n"
        "    BLOCK_MODE = str(lp.block_mode)\n"
        "    LEAGUE_BLOCKS_PER_MISSED_2PA = float(lp.league_blocks_per_missed_2pa)\n"
        "    N_PERIODS = int(lp.regulation_periods)\n"
        "    HALF_END = lp.half_end_periods\n",
        1,
    ),
    ("_player_usage_weights(", "_usage_w(", -1),  # every call site (the def keeps its name; fixed just below)
    ("def _usage_w(players: pd.DataFrame, col_pm: str, lineup_idx: List[int], *, lp: LeagueParams) -> np.ndarray:",
     "def _player_usage_weights(players: pd.DataFrame, col_pm: str, lineup_idx: List[int], *, lp: LeagueParams) -> np.ndarray:", 1),
    ("_team_rates_from_priors(home_players, cfg)", "_rates(home_players, cfg)", 1),
    ("_team_rates_from_priors(away_players, cfg)", "_rates(away_players, cfg)", 1),
    ("= _sample_lineup(\n", "= sample_lineup(\n", 2),
    ("flags = _rotation_windows(", "flags = _windows(", 1),
    ("if _block_drawn(rng,", "if _blk_drawn(rng,", 2),
    ("_player_rebound_credited(rng, bool(oreb))", "_reb_credited(rng, bool(oreb))", 4),
    # ---- PBP: FT multipliers (NBA guards errors; WNBA lets them propagate) ----------------------------------
    (
        "    try:\n        h_ft_mult = _ft_rate_multipliers(home_players, h_mins)\n        a_ft_mult = _ft_rate_multipliers(away_players, a_mins)\n    except Exception:\n        h_ft_mult = np.ones(len(home_players), dtype=float)\n        a_ft_mult = np.ones(len(away_players), dtype=float)\n",
        "    if lp.ft_mult_errors_neutral:\n        try:\n            h_ft_mult = _ft_rate_multipliers(home_players, h_mins)\n            a_ft_mult = _ft_rate_multipliers(away_players, a_mins)\n        except Exception:\n            h_ft_mult = np.ones(len(home_players), dtype=float)\n            a_ft_mult = np.ones(len(away_players), dtype=float)\n    else:\n        h_ft_mult = _ft_rate_multipliers(home_players, h_mins)\n        a_ft_mult = _ft_rate_multipliers(away_players, a_mins)\n",
        1,
    ),
    # ---- PBP: team prior on a target -------------------------------------------------------------------------
    (
        '        _stack = bool(getattr(cfg, "team_prior_stacks_on_target", True))\n',
        '        _stack = bool(getattr(cfg, "team_prior_stacks_on_target", True)) if lp.team_prior_stacks_on_target is None else bool(lp.team_prior_stacks_on_target)\n',
        1,
    ),
    # ---- PBP: block rates (league fallback, league-aware helper) ---------------------------------------------
    ("a_ft_mult if SHOOTER_FT_RATE else None)\n", "a_ft_mult if SHOOTER_FT_RATE else None, lp=lp)\n", 1),
    ("h_ft_mult if SHOOTER_FT_RATE else None)\n", "h_ft_mult if SHOOTER_FT_RATE else None, lp=lp)\n", 1),
    # ---- PBP: geometry --------------------------------------------------------------------------------------
    ('            "pts": np.zeros((4, n), dtype=int),\n            "reb": np.zeros((4, n), dtype=int),\n            "ast": np.zeros((4, n), dtype=int),\n            "threes": np.zeros((4, n), dtype=int),\n',
     '            "pts": np.zeros((N_PERIODS, n), dtype=int),\n            "reb": np.zeros((N_PERIODS, n), dtype=int),\n            "ast": np.zeros((N_PERIODS, n), dtype=int),\n            "threes": np.zeros((N_PERIODS, n), dtype=int),\n', 1),
    (
        "    quarter_seconds = 12 * 60\n    segment_seconds = 3 * 60\n    n_segments = 4\n    minute_seconds = 60\n    n_minutes = 12\n"
        "    home_q_seg_pts = np.zeros((4, n_segments), dtype=int)\n    away_q_seg_pts = np.zeros((4, n_segments), dtype=int)\n"
        "    home_q_min_pts = np.zeros((4, n_minutes), dtype=int)\n    away_q_min_pts = np.zeros((4, n_minutes), dtype=int)\n\n"
        "    # Overtime settings (NBA: 5 minutes)\n    ot_seconds = 5 * 60\n",
        "    quarter_seconds = int(lp.regulation_period_seconds)\n    segment_seconds = 3 * 60\n"
        "    n_segments = int(max(1, np.ceil(float(quarter_seconds) / float(segment_seconds))))\n    minute_seconds = 60\n"
        "    n_minutes = int(max(1, quarter_seconds // minute_seconds))\n"
        "    home_q_seg_pts = np.zeros((N_PERIODS, n_segments), dtype=int)\n    away_q_seg_pts = np.zeros((N_PERIODS, n_segments), dtype=int)\n"
        "    home_q_min_pts = np.zeros((N_PERIODS, n_minutes), dtype=int)\n    away_q_min_pts = np.zeros((N_PERIODS, n_minutes), dtype=int)\n\n"
        "    # Overtime settings (5 minutes in every league today)\n    ot_seconds = int(lp.overtime_period_seconds)\n",
        1,
    ),
    ("            if 1 <= int(q) <= 4:\n", "            if 1 <= int(q) <= N_PERIODS:\n", 3),
    (
        "        if quarters and len(quarters) >= 4:\n            gm = float(sum(float(getattr(qr, \"home_pts_mu\", (qr or {}).get(\"home_pts_mu\"))) + float(getattr(qr, \"away_pts_mu\", (qr or {}).get(\"away_pts_mu\"))) for qr in quarters[:4]))\n",
        "        if quarters and len(quarters) >= N_PERIODS:\n            gm = float(sum(float(getattr(qr, \"home_pts_mu\", (qr or {}).get(\"home_pts_mu\"))) + float(getattr(qr, \"away_pts_mu\", (qr or {}).get(\"away_pts_mu\"))) for qr in quarters[:N_PERIODS]))\n",
        1,
    ),
    ("                    base_q = float(game_mu_total) / 4.0\n", "                    base_q = float(game_mu_total) / float(N_PERIODS)\n", 1),
    # ---- PBP: _simulate_period takes the resume hooks -------------------------------------------------------
    (
        "    def _simulate_period(q: int, period_seconds: int, q_env_mult: float, q_pace_mult: float, blowout: bool) -> None:\n"
        "        nonlocal home_score, away_score\n\n"
        "        # Track an approximate game clock so we can bucket points into 3-minute intervals.\n"
        "        # This is intentionally lightweight (we don't emit full timestamps per event).\n"
        "        q_remaining = int(period_seconds)\n\n"
        "        # possessions_per_game is per-team; our loop simulates team-possessions.\n"
        "        base_poss = (2.0 * float(poss)) / 4.0\n"
        "        # Scale possessions by period length relative to a 12-minute quarter.\n"
        "        base_poss *= float(period_seconds) / float(quarter_seconds)\n"
        "        jitter = float(rng.normal(0.0, cfg.possessions_jitter))\n"
        "        q_poss = int(max(6, round(base_poss * q_pace_mult * (1.0 + jitter))))\n\n"
        "        for pidx in range(q_poss):\n"
        "            if pidx == 0:\n"
        "                offense_home = bool(rng.random() < 0.5)\n",
        "    def _simulate_period(\n"
        "        q: int,\n"
        "        period_seconds: int,\n"
        "        q_env_mult: float,\n"
        "        q_pace_mult: float,\n"
        "        blowout: bool,\n"
        "        start_remaining: Optional[int] = None,\n"
        "        first_offense_home: Optional[bool] = None,\n"
        "        first_h_line: Optional[List[int]] = None,\n"
        "        first_a_line: Optional[List[int]] = None,\n"
        "    ) -> None:\n"
        "        nonlocal home_score, away_score\n\n"
        "        # RESUME: start_remaining is the clock left in a period already under way; None = the whole period, the\n"
        "        # only value a pregame run ever passes (and then every expression below is the vendored one).\n"
        "        period_left = int(period_seconds) if start_remaining is None else int(start_remaining)\n\n"
        "        # Track an approximate game clock so we can bucket points into 3-minute intervals.\n"
        "        # This is intentionally lightweight (we don't emit full timestamps per event).\n"
        "        q_remaining = int(period_left)\n\n"
        "        # possessions_per_game is per-team; our loop simulates team-possessions.\n"
        "        base_poss = (2.0 * float(poss)) / float(N_PERIODS)\n"
        "        # Scale possessions by the time to play relative to a full regulation period.\n"
        "        base_poss *= float(period_left) / float(quarter_seconds)\n"
        "        jitter = float(rng.normal(0.0, cfg.possessions_jitter))\n"
        "        # The 6-possession floor is a full-period rule; a partial period may have none left.\n"
        "        q_poss = int(max(6 if start_remaining is None else 0, round(base_poss * q_pace_mult * (1.0 + jitter))))\n\n"
        "        for pidx in range(q_poss):\n"
        "            if pidx == 0:\n"
        "                offense_home = bool(rng.random() < 0.5) if first_offense_home is None else bool(first_offense_home)\n",
        1,
    ),
    # Fouled-out players (resume only) get no lineup weight; the first possession may carry the live five.
    (
        "            use_contextual_lineups = bool(\n",
        "            if h_out_idx:\n"
        "                home_context_w = np.asarray(home_context_w, dtype=float).copy()\n"
        "                home_context_w[h_out_idx] = 0.0\n"
        "            if a_out_idx:\n"
        "                away_context_w = np.asarray(away_context_w, dtype=float).copy()\n"
        "                away_context_w[a_out_idx] = 0.0\n\n"
        "            use_contextual_lineups = bool(\n",
        1,
        "pbp",
    ),
    (
        "                a_line = _pick_lineup_from_pool(away_lineups, away_lineup_weights, n_players=len(away_players))\n",
        "                a_line = _pick_lineup_from_pool(away_lineups, away_lineup_weights, n_players=len(away_players))\n"
        "            if pidx == 0 and first_h_line:\n"
        "                h_line = list(first_h_line)\n"
        "            if pidx == 0 and first_a_line:\n"
        "                a_line = list(first_a_line)\n",
        1,
        "pbp",
    ),
    ("                    avg_sec = float(period_seconds) / float(max(1, q_poss))\n", "                    avg_sec = float(period_left) / float(max(1, q_poss))\n", 1),
    # Late-clock rules: regulation and half ends, in league terms.
    ("                    is_reg = 1 <= int(q) <= 4\n", "                    is_reg = 1 <= int(q) <= N_PERIODS\n", 2),
    ("and close_game and (int(q) in (2, 4))\n", "and close_game and (int(q) in HALF_END)\n", 1),
    ("if is_reg and (int(q) in (2, 4)) and int(q_remaining) <= 45 and close_game:\n", "if is_reg and (int(q) in HALF_END) and int(q_remaining) <= 45 and close_game:\n", 1),
    # ---- PBP: the period loop, resumable ---------------------------------------------------------------------
    (
        "    for q in range(1, 5):\n        h_start = int(home_score)\n        a_start = int(away_score)\n",
        "    for q in range(1, N_PERIODS + 1):\n"
        "        if q < start_period:\n"
        "            # RESUME: a period already played contributes its real points and makes no draws.\n"
        "            home_q_pts.append(_state_pts(state.home_period_pts, q))\n"
        "            away_q_pts.append(_state_pts(state.away_period_pts, q))\n"
        "            continue\n"
        "        h_start = int(home_score)\n"
        "        a_start = int(away_score)\n"
        "        resuming_here = bool(q == start_period and not opening_tip)\n"
        "        if resuming_here:\n"
        "            # This period's points so far belong to it (the score already includes them).\n"
        "            h_start -= _state_pts(state.home_period_pts, q)\n"
        "            a_start -= _state_pts(state.away_period_pts, q)\n",
        1,
    ),
    (
        "        if q >= 4 and abs(margin) >= int(cfg.blowout_q4_margin):\n            blowout = True\n        if q >= 3 and abs(margin) >= int(cfg.blowout_margin):\n            blowout = True\n\n"
        "        _simulate_period(q=q, period_seconds=int(quarter_seconds), q_env_mult=float(q_env_mult), q_pace_mult=float(q_pace_mult), blowout=bool(blowout))\n",
        "        if q >= N_PERIODS and abs(margin) >= int(cfg.blowout_q4_margin):\n            blowout = True\n        if q >= int(lp.second_half_first_period) and abs(margin) >= int(cfg.blowout_margin):\n            blowout = True\n\n"
        "        if resuming_here:\n"
        "            _simulate_period(q=q, period_seconds=int(quarter_seconds), q_env_mult=float(q_env_mult), q_pace_mult=float(q_pace_mult), blowout=bool(blowout), **resume_kwargs)\n"
        "        else:\n"
        "            _simulate_period(q=q, period_seconds=int(quarter_seconds), q_env_mult=float(q_env_mult), q_pace_mult=float(q_pace_mult), blowout=bool(blowout))\n",
        1,
    ),
    (
        "        ot_n = 0\n        while int(home_score) == int(away_score) and ot_n < int(max_overtimes):\n            ot_n += 1\n            h_start = int(home_score)\n            a_start = int(away_score)\n\n"
        "            # Reuse last-known environment; keep it stable for OT.\n"
        "            _simulate_period(q=4 + int(ot_n), period_seconds=int(ot_seconds), q_env_mult=1.0, q_pace_mult=1.0, blowout=False)\n",
        "        ot_n = 0\n"
        "        resume_in_ot = bool(start_period > N_PERIODS)\n"
        "        if resume_in_ot:\n"
        "            # RESUME in overtime: earlier overtimes were played; record them without draws.\n"
        "            for p_done in range(N_PERIODS + 1, start_period):\n"
        "                home_ot_pts.append(_state_pts(state.home_period_pts, p_done))\n"
        "                away_ot_pts.append(_state_pts(state.away_period_pts, p_done))\n"
        "                ot_n += 1\n"
        "        while resume_in_ot or (int(home_score) == int(away_score) and ot_n < int(max_overtimes)):\n            ot_n += 1\n            h_start = int(home_score)\n            a_start = int(away_score)\n\n"
        "            # Reuse last-known environment; keep it stable for OT.\n"
        "            if resume_in_ot:\n"
        "                resume_in_ot = False\n"
        "                h_start -= _state_pts(state.home_period_pts, N_PERIODS + int(ot_n))\n"
        "                a_start -= _state_pts(state.away_period_pts, N_PERIODS + int(ot_n))\n"
        "                _simulate_period(q=N_PERIODS + int(ot_n), period_seconds=int(ot_seconds), q_env_mult=1.0, q_pace_mult=1.0, blowout=False, **resume_kwargs)\n"
        "            else:\n"
        "                _simulate_period(q=N_PERIODS + int(ot_n), period_seconds=int(ot_seconds), q_env_mult=1.0, q_pace_mult=1.0, blowout=False)\n",
        1,
    ),
    # ---- PBP: finalize writes one entry per regulation period -----------------------------------------------
    (
        '                    "q_pts": [int(qagg["pts"][0, i]), int(qagg["pts"][1, i]), int(qagg["pts"][2, i]), int(qagg["pts"][3, i])],\n',
        '                    "q_pts": [int(qagg["pts"][k, i]) for k in range(N_PERIODS)],\n',
        1,
    ),
    (
        '                    "q_reb": [int(qagg["reb"][0, i]), int(qagg["reb"][1, i]), int(qagg["reb"][2, i]), int(qagg["reb"][3, i])],\n',
        '                    "q_reb": [int(qagg["reb"][k, i]) for k in range(N_PERIODS)],\n',
        1,
    ),
    (
        '                    "q_ast": [int(qagg["ast"][0, i]), int(qagg["ast"][1, i]), int(qagg["ast"][2, i]), int(qagg["ast"][3, i])],\n',
        '                    "q_ast": [int(qagg["ast"][k, i]) for k in range(N_PERIODS)],\n',
        1,
    ),
    (
        '                    "q_threes": [int(qagg["threes"][0, i]), int(qagg["threes"][1, i]), int(qagg["threes"][2, i]), int(qagg["threes"][3, i])],\n',
        '                    "q_threes": [int(qagg["threes"][k, i]) for k in range(N_PERIODS)],\n',
        1,
    ),
    # ---- PBP: resume state set-up, after the aggregation arrays and before the score starts ----------------
    (
        "    home_score = 0\n    away_score = 0\n    home_q_pts: List[int] = []\n    away_q_pts: List[int] = []\n",
        "    # RESUME set-up. GameState() is the opening tip: score 0-0, period 1, nothing forced, no draws spent here.\n"
        "    state = state if state is not None else GameState()\n"
        "    state.validate(lp)\n"
        "    opening_tip = state.is_opening_tip(lp)\n"
        "    start_period = 1 if opening_tip else int(state.period)\n"
        "    resume_kwargs: Dict[str, Any] = {}\n"
        "    h_out_idx: List[int] = []\n"
        "    a_out_idx: List[int] = []\n"
        "    if not opening_tip:\n"
        "        full_left = state.period_seconds(lp)\n"
        "        left = None if state.seconds_remaining is None or int(state.seconds_remaining) == int(full_left) else int(state.seconds_remaining)\n"
        "        h_names = _player_names(home_players)\n"
        "        a_names = _player_names(away_players)\n"
        "        h_out = _fouled_out_names(state.home_player_fouls, lp)\n"
        "        a_out = _fouled_out_names(state.away_player_fouls, lp)\n"
        "        h_out_idx = [i for i, nm in enumerate(h_names) if nm in h_out]\n"
        "        a_out_idx = [i for i, nm in enumerate(a_names) if nm in a_out]\n"
        "        if h_out_idx:\n"
        "            home_lineups, home_lineup_weights = _drop_lineups_with(home_lineups, home_lineup_weights, set(h_out_idx))\n"
        "        if a_out_idx:\n"
        "            away_lineups, away_lineup_weights = _drop_lineups_with(away_lineups, away_lineup_weights, set(a_out_idx))\n"
        "        resume_kwargs = {\n"
        "            \"start_remaining\": left,\n"
        "            \"first_offense_home\": None if state.possession is None else bool(state.possession == \"home\"),\n"
        "            \"first_h_line\": _lineup_indices(h_names, state.home_on_floor, side=\"home\"),\n"
        "            \"first_a_line\": _lineup_indices(a_names, state.away_on_floor, side=\"away\"),\n"
        "        }\n\n"
        "    home_score = int(state.home_score)\n    away_score = int(state.away_score)\n    home_q_pts: List[int] = []\n    away_q_pts: List[int] = []\n",
        1,
    ),
]

FOOTER = '''

def _state_pts(period_pts: Tuple[int, ...], period: int) -> int:
    """Points a GameState records for a 1-based period; 0 for a period it has no entry for."""
    k = int(period) - 1
    return int(period_pts[k]) if 0 <= k < len(period_pts) else 0


def _player_names(players: pd.DataFrame) -> List[str]:
    return [str(x or "").strip() for x in players.get("player_name", pd.Series([""] * len(players)))]


def _lineup_indices(names: List[str], on_floor: Tuple[str, ...], *, side: str) -> Optional[List[int]]:
    """Indices of the live five in the player frame. A name not in the frame REFUSES (ValueError), never drops."""
    if not on_floor:
        return None
    index = {nm: i for i, nm in enumerate(names)}
    missing = [str(nm) for nm in on_floor if str(nm).strip() not in index]
    if missing:
        raise ValueError(f"GameState.{side}_on_floor names players not in the {side} player frame: {missing}")
    return [index[str(nm).strip()] for nm in on_floor]


def _drop_lineups_with(
    lineups: Optional[List[List[int]]], weights: Optional[np.ndarray], out: set
) -> Tuple[Optional[List[List[int]]], Optional[np.ndarray]]:
    """The lineup pool without any unit that contains a fouled-out player (weights kept aligned)."""
    if not lineups:
        return lineups, weights
    keep = [i for i, lu in enumerate(lineups) if not (set(int(x) for x in (lu or [])) & out)]
    w = None
    if weights is not None:
        arr = np.asarray(weights, dtype=float)
        w = np.asarray([arr[i] if i < arr.size else 1.0 for i in keep], dtype=float)
    return [lineups[i] for i in keep], w
'''


def build() -> str:
    text = stub_event_level(SRC.read_text(encoding="utf-8"))
    for edit in EDITS:
        anchor, repl, count = edit[:3]
        scope = edit[3] if len(edit) > 3 else "all"
        cut = text.find("def simulate_pbp_game_boxscore(") if scope == "pbp" else 0
        if cut < 0:
            raise SystemExit("cannot find the PBP simulator for a pbp-scoped edit")
        head, body = text[:cut], text[cut:]
        found = body.count(anchor)
        if count >= 0 and found != count:
            raise SystemExit(f"ANCHOR MISMATCH ({scope}): expected {count}, found {found}:\n{anchor[:300]}")
        if count < 0 and found == 0:
            raise SystemExit(f"ANCHOR MISSING ({scope}):\n{anchor[:300]}")
        text = head + body.replace(anchor, repl)
    return HEADER + text + FOOTER


EVENT_LEVEL_STUB = '''def simulate_event_level_boxscore(
    rng: np.random.Generator,
    home_players: pd.DataFrame,
    away_players: pd.DataFrame,
    home_q_pts: List[int],
    away_q_pts: List[int],
    cfg: Optional[EventSimConfig] = None,
    home_lineups: Optional[List[List[int]]] = None,
    home_lineup_weights: Optional[np.ndarray] = None,
    away_lineups: Optional[List[List[int]]] = None,
    away_lineup_weights: Optional[np.ndarray] = None,
    home_team_adj: Optional[Dict[str, float]] = None,
    away_team_adj: Optional[Dict[str, float]] = None,
    *,
    league: LeagueParams,
    sample_lineup: Optional[Callable[..., List[int]]] = None,
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """REFUSES. The legacy non-PBP simulator was never ported, because it never worked.

    In BOTH vendored copies it raised ``NameError: name 'period_seconds' is not
    defined`` on its first possession (vendored events.py:796 passes
    ``period_seconds=int(period_seconds)`` from a scope that has no
    ``period_seconds``), so every call failed, for every input. Measured
    2026-10-09, lane basketball-native-engine: 9 of 9 synthetic cases raised in
    the vendored engine. Production does not reach it: the smart sim runs
    ``use_pbp=True`` (REFRESH_PREDICT_PROPS_SMART_SIM_PBP defaults on). A
    caller that asks for it still fails, as before, but with a named refusal
    instead of a NameError.
    """
    raise NotImplementedError(
        "simulate_event_level_boxscore: the legacy non-PBP basketball simulator was broken in the vendored engine "
        "(NameError on its first possession) and is not ported; use simulate_pbp_game_boxscore (use_pbp=True)"
    )


'''


def stub_event_level(text: str) -> str:
    """Replace the vendored event-level simulator (broken, unreachable) with a named refusal."""
    start = text.find("def simulate_event_level_boxscore(")
    end = text.find("def _expected_points_per_possession(")
    if start < 0 or end < 0 or end <= start:
        raise SystemExit("could not locate the vendored event-level simulator")
    body = text[start:end]
    if "period_seconds=int(period_seconds)" not in body or "def _simulate_period" in body:
        raise SystemExit("the vendored event-level simulator changed: re-check that it still cannot run before stubbing it")
    return text[:start] + EVENT_LEVEL_STUB + text[end:]


def strip_switch_block(text: str) -> str:
    """Drop the vendored module-switch block (now LeagueParams); it must be found exactly once."""
    start = text.find("# ---------------------------------------------------------------------------------------------------------------\n# Engine fixes ported from the WNBA engine")
    end = text.find("def _ft_rate_multipliers(")
    if start < 0 or end < 0 or end <= start:
        raise SystemExit("could not locate the vendored switch block")
    note = (
        "# The vendored module switches (SHOOTER_FT_RATE, FOULED_MISS_NOT_FGA, EXACT_TARGET_CALIBRATION, TOV_PER_ATTEMPT,\n"
        "# PLAYER_REBOUND_CREDIT and its credits, BLOCK_MODE, LEAGUE_BLOCKS_PER_MISSED_2PA, BLOCK_RATE_ASSUMED_FG3_PCT,\n"
        "# BLOCK_ALLOC_BY_RATE / _FLOOR_PM) are LeagueParams fields now; see league.py for each one's provenance.\n\n\n"
    )
    return text[:start] + note + text[end:]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if engine.py differs from a fresh regeneration")
    args = ap.parse_args(argv)
    text = strip_switch_block(build())
    code = "\n".join(ln for ln in text.splitlines() if not ln.lstrip().startswith("#"))
    for leftover in ("BLOCK_RATE_ASSUMED_FG3_PCT", "OREB_PLAYER_CREDIT", "BLOCK_ALLOC_FLOOR_PM", "_sample_lineup(", "LEAGUE."):
        if leftover in code:
            raise SystemExit(f"LEFTOVER vendored token in the port: {leftover!r}")
    if args.check:
        same = DST.exists() and DST.read_text(encoding="utf-8") == text
        print("engine.py matches the port" if same else "engine.py DIFFERS from the port")
        return 0 if same else 1
    DST.write_bytes(text.encode("utf-8"))
    print(f"wrote {DST.relative_to(ROOT)} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
